window.vocab = [
  { kanji: "一", reading: { hiragana: "いち", katakana: "イチ" }, grade: 1, meaning: "ひとつ (1️⃣)" },
{ kanji: "一", reading: { hiragana: "いち", katakana: "イチ" }, grade: 1, meaning: "一・いち ➕1" },
{ kanji: "二", reading: { hiragana: "に", katakana: "ニ" }, grade: 1, meaning: "二・に ➕2" },
{ kanji: "三", reading: { hiragana: "さん", katakana: "サン" }, grade: 1, meaning: "三・さん ➕3" },
{ kanji: "四", reading: { hiragana: "し／よん", katakana: "シ／ヨン" }, grade: 1, meaning: "四・し／よん ➕4" },
{ kanji: "五", reading: { hiragana: "ご", katakana: "ゴ" }, grade: 1, meaning: "五・ご ➕5" },
{ kanji: "六", reading: { hiragana: "ろく", katakana: "ロク" }, grade: 1, meaning: "六・ろく ➕6" },
{ kanji: "七", reading: { hiragana: "しち／なな", katakana: "シチ／ナナ" }, grade: 1, meaning: "七・しち／なな ➕7" },
{ kanji: "八", reading: { hiragana: "はち", katakana: "ハチ" }, grade: 1, meaning: "八・はち ➕8" },
{ kanji: "九", reading: { hiragana: "きゅう／く", katakana: "キュウ／ク" }, grade: 1, meaning: "九・きゅう／く ➕9" },
{ kanji: "十", reading: { hiragana: "じゅう", katakana: "ジュウ" }, grade: 1, meaning: "十・じゅう ➕10" },
  { kanji: "百", reading: { hiragana: "ひゃく", katakana: "ヒャク" }, grade: 1, meaning: "ひゃく (💯)" },
  { kanji: "千", reading: { hiragana: "せん", katakana: "セン" }, grade: 1, meaning: "せん (1000️⃣)" },
{ kanji: "円", reading: { hiragana: "えん", katakana: "エン" }, grade: 1, meaning: "えん (💴)" },
  { kanji: "口", reading: { hiragana: "くち", katakana: "クチ" }, grade: 1, meaning: "くち (👄)" },
  { kanji: "目", reading: { hiragana: "め", katakana: "メ" }, grade: 1, meaning: "め (👁)" },
  { kanji: "耳", reading: { hiragana: "みみ", katakana: "ミミ" }, grade: 1, meaning: "みみ (👂)" },
  { kanji: "手", reading: { hiragana: "て", katakana: "テ" }, grade: 1, meaning: "て (✋)" },
  { kanji: "足", reading: { hiragana: "あし", katakana: "アシ" }, grade: 1, meaning: "あし (🦶)" },
  { kanji: "力", reading: { hiragana: "ちから", katakana: "チカラ" }, grade: 1, meaning: "ちから (💪)" },
  { kanji: "男", reading: { hiragana: "おとこ", katakana: "オトコ" }, grade: 1, meaning: "おとこ (👨)" },
  { kanji: "女", reading: { hiragana: "おんな", katakana: "オンナ" }, grade: 1, meaning: "おんな (👩)" },
  { kanji: "子", reading: { hiragana: "こ", katakana: "コ" }, grade: 1, meaning: "こども (🧒)" },
  { kanji: "人", reading: { hiragana: "ひと", katakana: "ヒト" }, grade: 1, meaning: "ひと (👤)" },
  { kanji: "日", reading: { hiragana: "ひ / にち", katakana: "ヒ / ニチ" }, grade: 1, meaning: "ひ (🌞)" },
  { kanji: "月", reading: { hiragana: "つき / げつ", katakana: "ツキ / ゲツ" }, grade: 1, meaning: "つき (🌙)" },
  { kanji: "火", reading: { hiragana: "ひ / か", katakana: "ヒ / カ" }, grade: 1, meaning: "ひ (🔥)" },
  { kanji: "水", reading: { hiragana: "みず / すい", katakana: "ミズ / スイ" }, grade: 1, meaning: "みず (💧)" },
  { kanji: "木", reading: { hiragana: "き / もく", katakana: "キ / モク" }, grade: 1, meaning: "き (🌳)" },
  { kanji: "金", reading: { hiragana: "かね / きん", katakana: "カネ / キン" }, grade: 1, meaning: "おかね・きん (💰🔔)" },
  { kanji: "土", reading: { hiragana: "つち / ど", katakana: "ツチ / ド" }, grade: 1, meaning: "つち (🌍)" },
  { kanji: "山", reading: { hiragana: "やま", katakana: "ヤマ" }, grade: 1, meaning: "やま (⛰)" },
  { kanji: "川", reading: { hiragana: "かわ", katakana: "カワ" }, grade: 1, meaning: "かわ (🏞)" },
  { kanji: "田", reading: { hiragana: "た", katakana: "タ" }, grade: 1, meaning: "たんぼ (🌾)" },
  { kanji: "天", reading: { hiragana: "てん", katakana: "テン" }, grade: 1, meaning: "てん (☁️)" },
{ kanji: "空", reading: { hiragana: "そら / くう", katakana: "ソラ / クウ" }, grade: 1, meaning: "そら (🌌✈️)" },
  { kanji: "生", reading: { hiragana: "せい / いきる", katakana: "セイ / イキル" }, grade: 1, meaning: "いきる・なま (🌱)" },
  { kanji: "花", reading: { hiragana: "はな", katakana: "ハナ" }, grade: 1, meaning: "はな (🌸)" },
  { kanji: "草", reading: { hiragana: "くさ", katakana: "クサ" }, grade: 1, meaning: "くさ (🌿)" },
  { kanji: "虫", reading: { hiragana: "むし", katakana: "ムシ" }, grade: 1, meaning: "むし (🐛)" },
  { kanji: "犬", reading: { hiragana: "いぬ", katakana: "イヌ" }, grade: 1, meaning: "いぬ (🐶)" },
  { kanji: "猫", reading: { hiragana: "ねこ", katakana: "ネコ" }, grade: 1, meaning: "ねこ (🐱)" },
  { kanji: "魚", reading: { hiragana: "さかな", katakana: "サカナ" }, grade: 1, meaning: "さかな (🐟)" },
  { kanji: "車", reading: { hiragana: "くるま", katakana: "クルマ" }, grade: 1, meaning: "くるま (🚗)" },
  { kanji: "校", reading: { hiragana: "こう", katakana: "コウ" }, grade: 1, meaning: "がっこう (🏫)" },
  { kanji: "本", reading: { hiragana: "ほん", katakana: "ホン" }, grade: 1, meaning: "ほん (📖)" }
];
