window.vocab = [
  { kanji: "一", reading: { hiragana: "いち", katakana: "イチ" }, grade: 1, meaning: "ひとつ" },
  { kanji: "二", reading: { hiragana: "に", katakana: "ニ" }, grade: 1, meaning: "ふたつ" },
  { kanji: "三", reading: { hiragana: "さん", katakana: "サン" }, grade: 1, meaning: "みっつ" },
  { kanji: "四", reading: { hiragana: "し", katakana: "シ" }, grade: 1, meaning: "よっつ" },
  { kanji: "五", reading: { hiragana: "ご", katakana: "ゴ" }, grade: 1, meaning: "いつつ" },
  { kanji: "六", reading: { hiragana: "ろく", katakana: "ロク" }, grade: 1, meaning: "むっつ" },
  { kanji: "七", reading: { hiragana: "しち", katakana: "シチ" }, grade: 1, meaning: "ななつ" },
  { kanji: "八", reading: { hiragana: "はち", katakana: "ハチ" }, grade: 1, meaning: "やっつ" },
  { kanji: "九", reading: { hiragana: "きゅう", katakana: "キュウ" }, grade: 1, meaning: "ここのつ" },
  { kanji: "十", reading: { hiragana: "じゅう", katakana: "ジュウ" }, grade: 1, meaning: "とお" },

  { kanji: "百", reading: { hiragana: "ひゃく", katakana: "ヒャク" }, grade: 1, meaning: "ひゃく" },
  { kanji: "千", reading: { hiragana: "せん", katakana: "セン" }, grade: 1, meaning: "せん" },
  { kanji: "円", reading: { hiragana: "えん", katakana: "エン" }, grade: 1, meaning: "おかね" },
  { kanji: "口", reading: { hiragana: "くち", katakana: "クチ" }, grade: 1, meaning: "くち" },
  { kanji: "目", reading: { hiragana: "め", katakana: "メ" }, grade: 1, meaning: "め" },
  { kanji: "耳", reading: { hiragana: "みみ", katakana: "ミミ" }, grade: 1, meaning: "みみ" },
  { kanji: "手", reading: { hiragana: "て", katakana: "テ" }, grade: 1, meaning: "て" },
  { kanji: "足", reading: { hiragana: "あし", katakana: "アシ" }, grade: 1, meaning: "あし" },
  { kanji: "目", reading: { hiragana: "め", katakana: "メ" }, grade: 1, meaning: "め" },
  { kanji: "力", reading: { hiragana: "ちから", katakana: "チカラ" }, grade: 1, meaning: "ちから" },

  { kanji: "男", reading: { hiragana: "おとこ", katakana: "オトコ" }, grade: 1, meaning: "おとこ" },
  { kanji: "女", reading: { hiragana: "おんな", katakana: "オンナ" }, grade: 1, meaning: "おんな" },
  { kanji: "子", reading: { hiragana: "こ", katakana: "コ" }, grade: 1, meaning: "こども" },
  { kanji: "人", reading: { hiragana: "ひと", katakana: "ヒト" }, grade: 1, meaning: "ひと" },
  { kanji: "日", reading: { hiragana: "ひ", katakana: "ヒ" }, grade: 1, meaning: "たいよう" },
  { kanji: "月", reading: { hiragana: "つき", katakana: "ツキ" }, grade: 1, meaning: "つき" },
  { kanji: "火", reading: { hiragana: "ひ", katakana: "ヒ" }, grade: 1, meaning: "ひ" },
  { kanji: "水", reading: { hiragana: "みず", katakana: "ミズ" }, grade: 1, meaning: "みず" },
  { kanji: "木", reading: { hiragana: "き", katakana: "キ" }, grade: 1, meaning: "き" },
  { kanji: "金", reading: { hiragana: "かね", katakana: "カネ" }, grade: 1, meaning: "おかね" },
  { kanji: "土", reading: { hiragana: "つち", katakana: "ツチ" }, grade: 1, meaning: "つち" },

  { kanji: "山", reading: { hiragana: "やま", katakana: "ヤマ" }, grade: 1, meaning: "やま" },
  { kanji: "川", reading: { hiragana: "かわ", katakana: "カワ" }, grade: 1, meaning: "かわ" },
  { kanji: "田", reading: { hiragana: "た", katakana: "タ" }, grade: 1, meaning: "たんぼ" },
  { kanji: "天", reading: { hiragana: "てん", katakana: "テン" }, grade: 1, meaning: "そら" },
  { kanji: "気", reading: { hiragana: "き", katakana: "キ" }, grade: 1, meaning: "きもち" },
  { kanji: "空", reading: { hiragana: "そら", katakana: "ソラ" }, grade: 1, meaning: "そら" },
  { kanji: "雨", reading: { hiragana: "あめ", katakana: "アメ" }, grade: 1, meaning: "あめ" },
  { kanji: "生", reading: { hiragana: "い", katakana: "イ" }, grade: 1, meaning: "いきる" },
  { kanji: "花", reading: { hiragana: "はな", katakana: "ハナ" }, grade: 1, meaning: "はな" },
  { kanji: "草", reading: { hiragana: "くさ", katakana: "クサ" }, grade: 1, meaning: "くさ" },

  { kanji: "虫", reading: { hiragana: "むし", katakana: "ムシ" }, grade: 1, meaning: "むし" },
  { kanji: "犬", reading: { hiragana: "いぬ", katakana: "イヌ" }, grade: 1, meaning: "いぬ" },
  { kanji: "名", reading: { hiragana: "な", katakana: "ナ" }, grade: 1, meaning: "なまえ" },
  { kanji: "立", reading: { hiragana: "た", katakana: "タ" }, grade: 1, meaning: "たつ" },
  { kanji: "見", reading: { hiragana: "み", katakana: "ミ" }, grade: 1, meaning: "みる" },
  { kanji: "音", reading: { hiragana: "おと", katakana: "オト" }, grade: 1, meaning: "おと" },
  { kanji: "力", reading: { hiragana: "ちから", katakana: "チカラ" }, grade: 1, meaning: "ちから" },
  { kanji: "車", reading: { hiragana: "くるま", katakana: "クルマ" }, grade: 1, meaning: "くるま" },
  { kanji: "校", reading: { hiragana: "こう", katakana: "コウ" }, grade: 1, meaning: "がっこう" },
  { kanji: "学", reading: { hiragana: "がく", katakana: "ガク" }, grade: 1, meaning: "まなぶ" },

  { kanji: "先", reading: { hiragana: "さき", katakana: "サキ" }, grade: 1, meaning: "まえ" },
  { kanji: "生", reading: { hiragana: "せい", katakana: "セイ" }, grade: 1, meaning: "いきる" },
  { kanji: "文", reading: { hiragana: "ぶん", katakana: "ブン" }, grade: 1, meaning: "もじ" },
  { kanji: "字", reading: { hiragana: "じ", katakana: "ジ" }, grade: 1, meaning: "もじ" },
  { kanji: "本", reading: { hiragana: "ほん", katakana: "ホン" }, grade: 1, meaning: "ほん" },
  { kanji: "正", reading: { hiragana: "ただ", katakana: "タダ" }, grade: 1, meaning: "ただしい" },
  { kanji: "休", reading: { hiragana: "やす", katakana: "ヤス" }, grade: 1, meaning: "やすむ" },
  { kanji: "先", reading: { hiragana: "さき", katakana: "サキ" }, grade: 1, meaning: "さき" },
  { kanji: "竹", reading: { hiragana: "たけ", katakana: "タケ" }, grade: 1, meaning: "たけ" },
  { kanji: "糸", reading: { hiragana: "いと", katakana: "イト" }, grade: 1, meaning: "いと" },

  { kanji: "貝", reading: { hiragana: "かい", katakana: "カイ" }, grade: 1, meaning: "かい" },
  { kanji: "石", reading: { hiragana: "いし", katakana: "イシ" }, grade: 1, meaning: "いし" },
  { kanji: "日", reading: { hiragana: "にち", katakana: "ニチ" }, grade: 1, meaning: "ひ" },
  { kanji: "入", reading: { hiragana: "い", katakana: "イ" }, grade: 1, meaning: "はいる" },
  { kanji: "出", reading: { hiragana: "で", katakana: "デ" }, grade: 1, meaning: "でる" },
  { kanji: "上", reading: { hiragana: "うえ", katakana: "ウエ" }, grade: 1, meaning: "うえ" },
  { kanji: "下", reading: { hiragana: "した", katakana: "シタ" }, grade: 1, meaning: "した" },
  { kanji: "左", reading: { hiragana: "ひだり", katakana: "ヒダリ" }, grade: 1, meaning: "ひだり" },
  { kanji: "右", reading: { hiragana: "みぎ", katakana: "ミギ" }, grade: 1, meaning: "みぎ" },
  { kanji: "大", reading: { hiragana: "おお", katakana: "オオ" }, grade: 1, meaning: "おおきい" },

  { kanji: "小", reading: { hiragana: "ちい", katakana: "チイ" }, grade: 1, meaning: "ちいさい" },
  { kanji: "中", reading: { hiragana: "なか", katakana: "ナカ" }, grade: 1, meaning: "なか" },
  { kanji: "山", reading: { hiragana: "やま", katakana: "ヤマ" }, grade: 1, meaning: "やま" },
  { kanji: "川", reading: { hiragana: "かわ", katakana: "カワ" }, grade: 1, meaning: "かわ" }
];
