window.vocab = [
  { kanji: "一", reading: { hiragana: "いち", katakana: "イチ" }, grade: 1, meaning: "一つ（ひとつ）", emoji: "1️⃣" },
  { kanji: "二", reading: { hiragana: "に", katakana: "ニ" }, grade: 1, meaning: "二つ（ふたつ）", emoji: "2️⃣" },
  { kanji: "三", reading: { hiragana: "さん", katakana: "サン" }, grade: 1, meaning: "三つ（みっつ）", emoji: "3️⃣" },
  { kanji: "四", reading: { hiragana: "し / よん", katakana: "シ / ヨン" }, grade: 1, meaning: "四つ（よっつ）", emoji: "4️⃣" },
  { kanji: "五", reading: { hiragana: "ご", katakana: "ゴ" }, grade: 1, meaning: "五つ（いつつ）", emoji: "5️⃣" },
  { kanji: "六", reading: { hiragana: "ろく", katakana: "ロク" }, grade: 1, meaning: "六つ（むっつ）", emoji: "6️⃣" },
  { kanji: "七", reading: { hiragana: "しち / なな", katakana: "シチ / ナナ" }, grade: 1, meaning: "七つ（ななつ）", emoji: "7️⃣" },
  { kanji: "八", reading: { hiragana: "はち", katakana: "ハチ" }, grade: 1, meaning: "八つ（やっつ）", emoji: "8️⃣" },
  { kanji: "九", reading: { hiragana: "きゅう / く", katakana: "キュウ / ク" }, grade: 1, meaning: "九つ（ここのつ）", emoji: "9️⃣" },
  { kanji: "十", reading: { hiragana: "じゅう", katakana: "ジュウ" }, grade: 1, meaning: "十（とお）", emoji: "🔟" },
  { kanji: "百", reading: { hiragana: "ひゃく", katakana: "ヒャク" }, grade: 1, meaning: "百（ひゃく）", emoji: "💯" },
  { kanji: "千", reading: { hiragana: "せん", katakana: "セン" }, grade: 1, meaning: "千（せん）", emoji: "🌊 (千=‘sen’, homophone for 川)" },
  { kanji: "上", reading: { hiragana: "うえ / あ(げる)", katakana: "ウエ / ア(ゲル)" }, grade: 1, meaning: "上（うえ）", emoji: "🔼" },
  { kanji: "下", reading: { hiragana: "した / さ(げる)", katakana: "シタ / サ(ゲル)" }, grade: 1, meaning: "下（した）", emoji: "🔽" },
  { kanji: "左", reading: { hiragana: "ひだり", katakana: "ヒダリ" }, grade: 1, meaning: "左（ひだり）", emoji: "🫲" },
  { kanji: "右", reading: { hiragana: "みぎ", katakana: "ミギ" }, grade: 1, meaning: "右（みぎ）", emoji: "🫱" },
  { kanji: "中", reading: { hiragana: "なか", katakana: "ナカ" }, grade: 1, meaning: "中（なか）", emoji: "🎯" },
  { kanji: "大", reading: { hiragana: "だい / おお(きい)", katakana: "ダイ / オオ(キイ)" }, grade: 1, meaning: "大きい（おおきい）", emoji: "🐘" },
  { kanji: "小", reading: { hiragana: "しょう / ちい(さい)", katakana: "ショウ / チイ(サイ)" }, grade: 1, meaning: "小さい（ちいさい）", emoji: "🐜" },
  { kanji: "月", reading: { hiragana: "つき / げつ", katakana: "ツキ / ゲツ" }, grade: 1, meaning: "月（つき）", emoji: "🌙" },
  { kanji: "日", reading: { hiragana: "ひ / にち", katakana: "ヒ / ニチ" }, grade: 1, meaning: "日（ひ）", emoji: "☀️" },
  { kanji: "年", reading: { hiragana: "とし / ねん", katakana: "トシ / ネン" }, grade: 1, meaning: "年（とし）", emoji: "📅" },
  { kanji: "早", reading: { hiragana: "はや(い)", katakana: "ハヤ(イ)" }, grade: 1, meaning: "早い（はやい）", emoji: "⏰" },
  { kanji: "木", reading: { hiragana: "き", katakana: "キ" }, grade: 1, meaning: "木（き）", emoji: "🌳" },
  { kanji: "林", reading: { hiragana: "はやし", katakana: "ハヤシ" }, grade: 1, meaning: "林（はやし）", emoji: "🌲🌲" },
  { kanji: "山", reading: { hiragana: "やま", katakana: "ヤマ" }, grade: 1, meaning: "山（やま）", emoji: "⛰️" },
  { kanji: "川", reading: { hiragana: "かわ", katakana: "カワ" }, grade: 1, meaning: "川（かわ）", emoji: "🌊" },
  { kanji: "土", reading: { hiragana: "つち", katakana: "ツチ" }, grade: 1, meaning: "土（つち）", emoji: "🟫" },
  { kanji: "空", reading: { hiragana: "そら", katakana: "ソラ" }, grade: 1, meaning: "空（そら）", emoji: "☁️" },
  { kanji: "田", reading: { hiragana: "た", katakana: "タ" }, grade: 1, meaning: "田（た）", emoji: "🌾" },
  { kanji: "天", reading: { hiragana: "てん", katakana: "テン" }, grade: 1, meaning: "天（てん）", emoji: "👼" },
  { kanji: "生", reading: { hiragana: "い(きる)", katakana: "イ(キル)" }, grade: 1, meaning: "生きる（いきる）", emoji: "🎂" },
  { kanji: "花", reading: { hiragana: "はな", katakana: "ハナ" }, grade: 1, meaning: "花（はな）", emoji: "🌸" },
  { kanji: "草", reading: { hiragana: "くさ", katakana: "クサ" }, grade: 1, meaning: "草（くさ）", emoji: "🌿" },
  { kanji: "虫", reading: { hiragana: "むし", katakana: "ムシ" }, grade: 1, meaning: "虫（むし）", emoji: "🐛" },
  { kanji: "犬", reading: { hiragana: "いぬ", katakana: "イヌ" }, grade: 1, meaning: "犬（いぬ）", emoji: "🐕" },
  { kanji: "人", reading: { hiragana: "ひと", katakana: "ヒト" }, grade: 1, meaning: "人（ひと）", emoji: "👤" },
  { kanji: "名", reading: { hiragana: "な", katakana: "ナ" }, grade: 1, meaning: "名前（なまえ）", emoji: "📛" },
  { kanji: "女", reading: { hiragana: "おんな", katakana: "オンナ" }, grade: 1, meaning: "女（おんな）", emoji: "👩" },
  { kanji: "男", reading: { hiragana: "おとこ", katakana: "オトコ" }, grade: 1, meaning: "男（おとこ）", emoji: "👨" },
  { kanji: "子", reading: { hiragana: "こ", katakana: "コ" }, grade: 1, meaning: "子供（こども）", emoji: "👶" },
  { kanji: "目", reading: { hiragana: "め", katakana: "メ" }, grade: 1, meaning: "目（め）", emoji: "👀" },
  { kanji: "耳", reading: { hiragana: "みみ", katakana: "ミミ" }, grade: 1, meaning: "耳（みみ）", emoji: "👂" },
  { kanji: "口", reading: { hiragana: "くち", katakana: "クチ" }, grade: 1, meaning: "口（くち）", emoji: "👄" },
  { kanji: "手", reading: { hiragana: "て", katakana: "テ" }, grade: 1, meaning: "手（て）", emoji: "✋" },
  { kanji: "足", reading: { hiragana: "あし", katakana: "アシ" }, grade: 1, meaning: "足（あし）", emoji: "🦶" },
  { kanji: "力", reading: { hiragana: "ちから", katakana: "チカラ" }, grade: 1, meaning: "力（ちから）", emoji: "💪" },
  { kanji: "雨", reading: { hiragana: "あめ", katakana: "アメ" }, grade: 1, meaning: "雨（あめ）", emoji: "🌧️" },
  { kanji: "電", reading: { hiragana: "でん", katakana: "デン" }, grade: 1, meaning: "電気（でんき）", emoji: "⚡" },
  { kanji: "車", reading: { hiragana: "くるま", katakana: "クルマ" }, grade: 1, meaning: "車（くるま）", emoji: "🚗" },
  { kanji: "火", reading: { hiragana: "ひ", katakana: "ヒ" }, grade: 1, meaning: "火（ひ）", emoji: "🔥" },
  { kanji: "水", reading: { hiragana: "みず", katakana: "ミズ" }, grade: 1, meaning: "水（みず）", emoji: "💧" },
  { kanji: "金", reading: { hiragana: "かね / きん", katakana: "カネ / キン" }, grade: 1, meaning: "お金（おかね）", emoji: "💰" },
  { kanji: "本", reading: { hiragana: "ほん", katakana: "ホン" }, grade: 1, meaning: "本（ほん）", emoji: "📖" },
  { kanji: "村", reading: { hiragana: "むら", katakana: "ムラ" }, grade: 1, meaning: "村（むら）", emoji: "🏡" },
  { kanji: "町", reading: { hiragana: "まち", katakana: "マチ" }, grade: 1, meaning: "町（まち）", emoji: "🏘️" },
  { kanji: "森", reading: { hiragana: "もり", katakana: "モリ" }, grade: 1, meaning: "森（もり）", emoji: "🌲🌳🌲" },
  { kanji: "正", reading: { hiragana: "ただ(しい)", katakana: "タダ(シイ)" }, grade: 1, meaning: "正しい（ただしい）", emoji: "✅" },
  { kanji: "立", reading: { hiragana: "た(つ)", katakana: "タ(ツ)" }, grade: 1, meaning: "立つ（たつ）", emoji: "🧍" },
  { kanji: "休", reading: { hiragana: "やす(む)", katakana: "ヤス(ム)" }, grade: 1, meaning: "休む（やすむ）", emoji: "🛌" },
  { kanji: "先", reading: { hiragana: "さき", katakana: "サキ" }, grade: 1, meaning: "先（さき）", emoji: "⏭️" },
  { kanji: "学", reading: { hiragana: "がく", katakana: "ガク" }, grade: 1, meaning: "学校（がっこう）", emoji: "🎓" },
  { kanji: "校", reading: { hiragana: "こう", katakana: "コウ" }, grade: 1, meaning: "学校（がっこう）", emoji: "🏫" },
  { kanji: "見", reading: { hiragana: "み(る)", katakana: "ミ(ル)" }, grade: 1, meaning: "見る（みる）", emoji: "👁️" },
  { kanji: "聞", reading: { hiragana: "き(く)", katakana: "キ(ク)" }, grade: 1, meaning: "聞く（きく）", emoji: "👂" },
  { kanji: "行", reading: { hiragana: "い(く)", katakana: "イ(ク)" }, grade: 1, meaning: "行く（いく）", emoji: "🚶" },
  { kanji: "来", reading: { hiragana: "く(る)", katakana: "ク(ル)" }, grade: 1, meaning: "来る（くる）", emoji: "➡️" },
  { kanji: "食", reading: { hiragana: "た(べる)", katakana: "タ(ベル)" }, grade: 1, meaning: "食べる（たべる）", emoji: "🍚" },
  { kanji: "飲", reading: { hiragana: "の(む)", katakana: "ノ(ム)" }, grade: 1, meaning: "飲む（のむ）", emoji: "🍵" },
  { kanji: "出", reading: { hiragana: "で(る)", katakana: "デ(ル)" }, grade: 1, meaning: "出る（でる）", emoji: "🚪" },
  { kanji: "入", reading: { hiragana: "はい(る)", katakana: "ハイ(ル)" }, grade: 1, meaning: "入る（はいる）", emoji: "🚶‍♂️➡️" },
  { kanji: "書", reading: { hiragana: "か(く)", katakana: "カ(ク)" }, grade: 1, meaning: "書く（かく）", emoji: "✍️" },
  { kanji: "読", reading: { hiragana: "よ(む)", katakana: "ヨ(ム)" }, grade: 1, meaning: "読む（よむ）", emoji: "📖" },
  { kanji: "話", reading: { hiragana: "はな(す)", katakana: "ハナ(ス)" }, grade: 1, meaning: "話す（はなす）", emoji: "🗣️" },
  { kanji: "友", reading: { hiragana: "とも", katakana: "トモ" }, grade: 1, meaning: "友達（ともだち）", emoji: "👫" },
  { kanji: "父", reading: { hiragana: "ちち", katakana: "チチ" }, grade: 1, meaning: "父（ちち）", emoji: "👨" },
  { kanji: "母", reading: { hiragana: "はは", katakana: "ハハ" }, grade: 1, meaning: "母（はは）", emoji: "👩" },
  { kanji: "気", reading: { hiragana: "き", katakana: "キ" }, grade: 1, meaning: "元気（げんき）", emoji: "💨" },
  { kanji: "円", reading: { hiragana: "えん", katakana: "エン" }, grade: 1, meaning: "円（えん）", emoji: "💴" },
  { kanji: "玉", reading: { hiragana: "たま", katakana: "タマ" }, grade: 1, meaning: "玉（たま）", emoji: "🔮" },
  { kanji: "音", reading: { hiragana: "おと", katakana: "オト" }, grade: 1, meaning: "音（おと）", emoji: "🎵" },
  { kanji: "校", reading: { hiragana: "こう", katakana: "コウ" }, grade: 1, meaning: "学校（がっこう）", emoji: "🏫" },
  { kanji: "間", reading: { hiragana: "あいだ", katakana: "アイダ" }, grade: 1, meaning: "間（あいだ）", emoji: "⏳" },
  { kanji: "時", reading: { hiragana: "とき", katakana: "トキ" }, grade: 1, meaning: "時間（じかん）", emoji: "⏰" },
  { kanji: "分", reading: { hiragana: "ふん / わ(かる)", katakana: "フン / ワ(カル)" }, grade: 1, meaning: "分かる（わかる）", emoji: "🤔" },
  { kanji: "長", reading: { hiragana: "なが(い)", katakana: "ナガ(イ)" }, grade: 1, meaning: "長い（ながい）", emoji: "📏" },
  { kanji: "高", reading: { hiragana: "たか(い)", katakana: "タカ(イ)" }, grade: 1, meaning: "高い（たかい）", emoji: "📈" },
  { kanji: "国", reading: { hiragana: "くに", katakana: "クニ" }, grade: 1, meaning: "国（くに）", emoji: "🗺️" },
  { kanji: "語", reading: { hiragana: "ご", katakana: "ゴ" }, grade: 1, meaning: "日本語（にほんご）", emoji: "🗣️" },
  { kanji: "文", reading: { hiragana: "ぶん", katakana: "ブン" }, grade: 1, meaning: "文（ぶん）", emoji: "📝" },
  { kanji: "字", reading: { hiragana: "じ", katakana: "ジ" }, grade: 1, meaning: "漢字（かんじ）", emoji: "🔤" },
  { kanji: "白", reading: { hiragana: "しろ", katakana: "シロ" }, grade: 1, meaning: "白い（しろい）", emoji: "⚪" },
  { kanji: "赤", reading: { hiragana: "あか", katakana: "アカ" }, grade: 1, meaning: "赤い（あかい）", emoji: "🔴" },
  { kanji: "青", reading: { hiragana: "あお", katakana: "アオ" }, grade: 1, meaning: "青い（あおい）", emoji: "🔵" },
  { kanji: "色", reading: { hiragana: "いろ", katakana: "イロ" }, grade: 1, meaning: "色（いろ）", emoji: "🎨" },
  { kanji: "貝", reading: { hiragana: "かい", katakana: "カイ" }, grade: 1, meaning: "貝（かい）", emoji: "🐚" },
  { kanji: "魚", reading: { hiragana: "さかな", katakana: "サカナ" }, grade: 1, meaning: "魚（さかな）", emoji: "🐟" },
  { kanji: "鳥", reading: { hiragana: "とり", katakana: "トリ" }, grade: 1, meaning: "鳥（とり）", emoji: "🐦" },
  { kanji: "馬", reading: { hiragana: "うま", katakana: "ウマ" }, grade: 1, meaning: "馬（うま）", emoji: "🐴" },
  { kanji: "牛", reading: { hiragana: "うし", katakana: "ウシ" }, grade: 1, meaning: "牛（うし）", emoji: "🐮" },
  { kanji: "外", reading: { hiragana: "そと", katakana: "ソト" }, grade: 1, meaning: "外（そと）", emoji: "🚪" },
  { kanji: "多", reading: { hiragana: "おお(い)", katakana: "オオ(イ)" }, grade: 1, meaning: "多い（おおい）", emoji: "🔢" },
  { kanji: "少", reading: { hiragana: "すこ(し)", katakana: "スコ(シ)" }, grade: 1, meaning: "少し（すこし）", emoji: "👌" },
  { kanji: "古", reading: { hiragana: "ふる(い)", katakana: "フル(イ)" }, grade: 1, meaning: "古い（ふるい）", emoji: "🏚️" },
  { kanji: "新", reading: { hiragana: "あたら(しい)", katakana: "アタラ(シイ)" }, grade: 1, meaning: "新しい（あたらしい）", emoji: "🆕" },
  { kanji: "同", reading: { hiragana: "おな(じ)", katakana: "オナ(ジ)" }, grade: 1, meaning: "同じ（おなじ）", emoji: "🔄" },
  { kanji: "何", reading: { hiragana: "なに", katakana: "ナニ" }, grade: 1, meaning: "何（なに）", emoji: "❓" },
  
  { "kanji": "引", "reading": { "hiragana": "ひく", "katakana": "ヒク" }, "onyomi": "イン", "grade": 2, "meaning": "ひく", "emoji": "👆" },
  { "kanji": "羽", "reading": { "hiragana": "はね", "katakana": "ハネ" }, "onyomi": "ウ", "grade": 2, "meaning": "はね", "emoji": "🪶" },
  { "kanji": "雲", "reading": { "hiragana": "くも", "katakana": "クモ" }, "onyomi": "ウン", "grade": 2, "meaning": "くも", "emoji": "☁️" },
  { "kanji": "園", "reading": { "hiragana": "その", "katakana": "ソノ" }, "onyomi": "エン", "grade": 2, "meaning": "こうえん", "emoji": "🏡" },
  { "kanji": "遠", "reading": { "hiragana": "とおい", "katakana": "トオイ" }, "onyomi": "エン", "grade": 2, "meaning": "とおい", "emoji": "🔭" },
  { "kanji": "何", "reading": { "hiragana": "なに", "katakana": "ナニ" }, "onyomi": "カ", "grade": 2, "meaning": "なに", "emoji": "❓" },
  { "kanji": "科", "reading": { "hiragana": "か", "katakana": "カ" }, "onyomi": "カ", "grade": 2, "meaning": "かがく", "emoji": "🔬" },
  { "kanji": "夏", "reading": { "hiragana": "なつ", "katakana": "ナツ" }, "onyomi": "カ", "grade": 2, "meaning": "なつ", "emoji": "☀️" },
  { "kanji": "家", "reading": { "hiragana": "いえ", "katakana": "イエ" }, "onyomi": "カ", "grade": 2, "meaning": "いえ", "emoji": "🏠" },
  { "kanji": "歌", "reading": { "hiragana": "うた", "katakana": "ウタ" }, "onyomi": "カ", "grade": 2, "meaning": "うた", "emoji": "🎤" },
  { "kanji": "画", "reading": { "hiragana": "えがく", "katakana": "エガク" }, "onyomi": "ガ", "grade": 2, "meaning": "え", "emoji": "🎨" },
  { "kanji": "回", "reading": { "hiragana": "まわる", "katakana": "マワル" }, "onyomi": "カイ", "grade": 2, "meaning": "まわる", "emoji": "🔄" },
  { "kanji": "会", "reading": { "hiragana": "あう", "katakana": "アウ" }, "onyomi": "カイ", "grade": 2, "meaning": "あう", "emoji": "🤝" },
  { "kanji": "海", "reading": { "hiragana": "うみ", "katakana": "ウミ" }, "onyomi": "カイ", "grade": 2, "meaning": "うみ", "emoji": "🌊" },
  { "kanji": "絵", "reading": { "hiragana": "え", "katakana": "エ" }, "onyomi": "カイ", "grade": 2, "meaning": "え", "emoji": "🖼️" },
  { "kanji": "外", "reading": { "hiragana": "そと", "katakana": "ソト" }, "onyomi": "ガイ", "grade": 2, "meaning": "そと", "emoji": "🚪" },
  { "kanji": "角", "reading": { "hiragana": "かど", "katakana": "カド" }, "onyomi": "カク", "grade": 2, "meaning": "かど", "emoji": "📐" },
  { "kanji": "楽", "reading": { "hiragana": "たのしい", "katakana": "タノシイ" }, "onyomi": "ガク", "grade": 2, "meaning": "たのしい", "emoji": "🎵" },
  { "kanji": "活", "reading": { "hiragana": "いきる", "katakana": "イキル" }, "onyomi": "カツ", "grade": 2, "meaning": "いきる", "emoji": "💪" },
  { "kanji": "間", "reading": { "hiragana": "あいだ", "katakana": "アイダ" }, "onyomi": "カン", "grade": 2, "meaning": "あいだ", "emoji": "⏳" },
  { "kanji": "丸", "reading": { "hiragana": "まる", "katakana": "マル" }, "onyomi": "ガン", "grade": 2, "meaning": "まる", "emoji": "⚪" },
  { "kanji": "岩", "reading": { "hiragana": "いわ", "katakana": "イワ" }, "onyomi": "ガン", "grade": 2, "meaning": "いわ", "emoji": "🪨" },
  { "kanji": "顔", "reading": { "hiragana": "かお", "katakana": "カオ" }, "onyomi": "ガン", "grade": 2, "meaning": "かお", "emoji": "😀" },
  { "kanji": "汽", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 2, "meaning": "きかん", "emoji": "🚂" },
  { "kanji": "記", "reading": { "hiragana": "しるす", "katakana": "シルス" }, "onyomi": "キ", "grade": 2, "meaning": "きろく", "emoji": "📝" },
  { "kanji": "帰", "reading": { "hiragana": "かえる", "katakana": "カエル" }, "onyomi": "キ", "grade": 2, "meaning": "かえる", "emoji": "🏠" },
  { "kanji": "弓", "reading": { "hiragana": "ゆみ", "katakana": "ユミ" }, "onyomi": "キュウ", "grade": 2, "meaning": "ゆみ", "emoji": "🏹" },
  { "kanji": "牛", "reading": { "hiragana": "うし", "katakana": "ウシ" }, "onyomi": "ギュウ", "grade": 2, "meaning": "うし", "emoji": "🐄" },
  { "kanji": "魚", "reading": { "hiragana": "さかな", "katakana": "サカナ" }, "onyomi": "ギョ", "grade": 2, "meaning": "さかな", "emoji": "🐟" },
  { "kanji": "京", "reading": { "hiragana": "きょう", "katakana": "キョウ" }, "onyomi": "キョウ", "grade": 2, "meaning": "きょうと", "emoji": "🏙️" },
  { "kanji": "強", "reading": { "hiragana": "つよい", "katakana": "ツヨイ" }, "onyomi": "キョウ", "grade": 2, "meaning": "つよい", "emoji": "💪" },
  { "kanji": "教", "reading": { "hiragana": "おしえる", "katakana": "オシエル" }, "onyomi": "キョウ", "grade": 2, "meaning": "おしえる", "emoji": "📚" },
  { "kanji": "近", "reading": { "hiragana": "ちかい", "katakana": "チカイ" }, "onyomi": "キン", "grade": 2, "meaning": "ちかい", "emoji": "📍" },
  { "kanji": "兄", "reading": { "hiragana": "あに", "katakana": "アニ" }, "onyomi": "ケイ", "grade": 2, "meaning": "あに", "emoji": "👦" },
  { "kanji": "形", "reading": { "hiragana": "かたち", "katakana": "カタチ" }, "onyomi": "ケイ", "grade": 2, "meaning": "かたち", "emoji": "🔷" },
  { "kanji": "計", "reading": { "hiragana": "はかる", "katakana": "ハカル" }, "onyomi": "ケイ", "grade": 2, "meaning": "はかる", "emoji": "📏" },
  { "kanji": "元", "reading": { "hiragana": "もと", "katakana": "モト" }, "onyomi": "ゲン", "grade": 2, "meaning": "もと", "emoji": "⏮️" },
  { "kanji": "言", "reading": { "hiragana": "いう", "katakana": "イウ" }, "onyomi": "ゲン", "grade": 2, "meaning": "いう", "emoji": "🗨️" },
  { "kanji": "原", "reading": { "hiragana": "はら", "katakana": "ハラ" }, "onyomi": "ゲン", "grade": 2, "meaning": "はら", "emoji": "🌄" },
  { "kanji": "戸", "reading": { "hiragana": "と", "katakana": "ト" }, "onyomi": "コ", "grade": 2, "meaning": "と", "emoji": "🚪" },
  { "kanji": "古", "reading": { "hiragana": "ふるい", "katakana": "フルイ" }, "onyomi": "コ", "grade": 2, "meaning": "ふるい", "emoji": "🏚️" },
  { "kanji": "午", "reading": { "hiragana": "ご", "katakana": "ゴ" }, "onyomi": "ゴ", "grade": 2, "meaning": "ごぜん", "emoji": "🕛" },
  { "kanji": "後", "reading": { "hiragana": "あと", "katakana": "アト" }, "onyomi": "ゴ", "grade": 2, "meaning": "あと", "emoji": "⏭️" },
  { "kanji": "語", "reading": { "hiragana": "かたる", "katakana": "カタル" }, "onyomi": "ゴ", "grade": 2, "meaning": "ことば", "emoji": "🗣️" },
  { "kanji": "工", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 2, "meaning": "こうじょう", "emoji": "🔧" },
  { "kanji": "公", "reading": { "hiragana": "おおやけ", "katakana": "オオヤケ" }, "onyomi": "コウ", "grade": 2, "meaning": "こうこう", "emoji": "🏛️" },
  { "kanji": "広", "reading": { "hiragana": "ひろい", "katakana": "ヒロイ" }, "onyomi": "コウ", "grade": 2, "meaning": "ひろい", "emoji": "↔️" },
  { "kanji": "交", "reading": { "hiragana": "まじわる", "katakana": "マジワル" }, "onyomi": "コウ", "grade": 2, "meaning": "まじわる", "emoji": "🔄" },
  { "kanji": "光", "reading": { "hiragana": "ひかり", "katakana": "ヒカリ" }, "onyomi": "コウ", "grade": 2, "meaning": "ひかり", "emoji": "💡" },
  { "kanji": "考", "reading": { "hiragana": "かんがえる", "katakana": "カンガエル" }, "onyomi": "コウ", "grade": 2, "meaning": "かんがえる", "emoji": "🤔" },
  { "kanji": "行", "reading": { "hiragana": "いく", "katakana": "イク" }, "onyomi": "コウ", "grade": 2, "meaning": "いく", "emoji": "🚶" },
  { "kanji": "高", "reading": { "hiragana": "たかい", "katakana": "タカイ" }, "onyomi": "コウ", "grade": 2, "meaning": "たかい", "emoji": "📈" },
  { "kanji": "黄", "reading": { "hiragana": "きいろ", "katakana": "キイロ" }, "onyomi": "コウ", "grade": 2, "meaning": "きいろ", "emoji": "💛" },
  { "kanji": "合", "reading": { "hiragana": "あう", "katakana": "アウ" }, "onyomi": "ゴウ", "grade": 2, "meaning": "あう", "emoji": "➕" },
  { "kanji": "谷", "reading": { "hiragana": "たに", "katakana": "タニ" }, "onyomi": "コク", "grade": 2, "meaning": "たに", "emoji": "🏞️" },
  { "kanji": "国", "reading": { "hiragana": "くに", "katakana": "クニ" }, "onyomi": "コク", "grade": 2, "meaning": "くに", "emoji": "🇯🇵" },
  { "kanji": "黒", "reading": { "hiragana": "くろ", "katakana": "クロ" }, "onyomi": "コク", "grade": 2, "meaning": "くろ", "emoji": "⚫" },
  { "kanji": "今", "reading": { "hiragana": "いま", "katakana": "イマ" }, "onyomi": "コン", "grade": 2, "meaning": "いま", "emoji": "⏱️" },
  { "kanji": "才", "reading": { "hiragana": "さい", "katakana": "サイ" }, "onyomi": "サイ", "grade": 2, "meaning": "さいのう", "emoji": "🧠" },
  { "kanji": "細", "reading": { "hiragana": "ほそい", "katakana": "ホソイ" }, "onyomi": "サイ", "grade": 2, "meaning": "ほそい", "emoji": "🧵" },
  { "kanji": "作", "reading": { "hiragana": "つくる", "katakana": "ツクル" }, "onyomi": "サク", "grade": 2, "meaning": "つくる", "emoji": "🛠️" },
  { "kanji": "算", "reading": { "hiragana": "さん", "katakana": "サン" }, "onyomi": "サン", "grade": 2, "meaning": "けいさん", "emoji": "🧮" },
  { "kanji": "止", "reading": { "hiragana": "とまる", "katakana": "トマル" }, "onyomi": "シ", "grade": 2, "meaning": "とまる", "emoji": "🛑" },
  { "kanji": "市", "reading": { "hiragana": "いち", "katakana": "イチ" }, "onyomi": "シ", "grade": 2, "meaning": "いち", "emoji": "🏙️" },
  { "kanji": "矢", "reading": { "hiragana": "や", "katakana": "ヤ" }, "onyomi": "シ", "grade": 2, "meaning": "や", "emoji": "🏹" },
  { "kanji": "姉", "reading": { "hiragana": "あね", "katakana": "アネ" }, "onyomi": "シ", "grade": 2, "meaning": "あね", "emoji": "👩" },
  { "kanji": "思", "reading": { "hiragana": "おもう", "katakana": "オモウ" }, "onyomi": "シ", "grade": 2, "meaning": "おもう", "emoji": "💭" },
  { "kanji": "紙", "reading": { "hiragana": "かみ", "katakana": "カミ" }, "onyomi": "シ", "grade": 2, "meaning": "かみ", "emoji": "📄" },
  { "kanji": "寺", "reading": { "hiragana": "てら", "katakana": "テラ" }, "onyomi": "ジ", "grade": 2, "meaning": "てら", "emoji": "🛕" },
  { "kanji": "時", "reading": { "hiragana": "とき", "katakana": "トキ" }, "onyomi": "ジ", "grade": 2, "meaning": "とき", "emoji": "⏰" },
  { "kanji": "自", "reading": { "hiragana": "みずから", "katakana": "ミズカラ" }, "onyomi": "ジ", "grade": 2, "meaning": "じぶん", "emoji": "🔄" },
  { "kanji": "室", "reading": { "hiragana": "しつ", "katakana": "シツ" }, "onyomi": "シツ", "grade": 2, "meaning": "へや", "emoji": "🚪" },
  { "kanji": "社", "reading": { "hiragana": "やしろ", "katakana": "ヤシロ" }, "onyomi": "シャ", "grade": 2, "meaning": "しゃかい", "emoji": "🏢" },
  { "kanji": "弱", "reading": { "hiragana": "よわい", "katakana": "ヨワイ" }, "onyomi": "ジャク", "grade": 2, "meaning": "よわい", "emoji": "🥺" },
  { "kanji": "首", "reading": { "hiragana": "くび", "katakana": "クビ" }, "onyomi": "シュ", "grade": 2, "meaning": "くび", "emoji": "👤" },
  { "kanji": "秋", "reading": { "hiragana": "あき", "katakana": "アキ" }, "onyomi": "シュウ", "grade": 2, "meaning": "あき", "emoji": "🍂" },
  { "kanji": "週", "reading": { "hiragana": "しゅう", "katakana": "シュウ" }, "onyomi": "シュウ", "grade": 2, "meaning": "しゅう", "emoji": "🗓️" },
  { "kanji": "春", "reading": { "hiragana": "はる", "katakana": "ハル" }, "onyomi": "シュン", "grade": 2, "meaning": "はる", "emoji": "🌸" },
  { "kanji": "書", "reading": { "hiragana": "かく", "katakana": "カク" }, "onyomi": "ショ", "grade": 2, "meaning": "かく", "emoji": "✍️" },
  { "kanji": "少", "reading": { "hiragana": "すこし", "katakana": "スコシ" }, "onyomi": "ショウ", "grade": 2, "meaning": "すこし", "emoji": "🔻" },
  { "kanji": "場", "reading": { "hiragana": "ば", "katakana": "バ" }, "onyomi": "ジョウ", "grade": 2, "meaning": "ばしょ", "emoji": "📍" },
  { "kanji": "色", "reading": { "hiragana": "いろ", "katakana": "イロ" }, "onyomi": "ショク", "grade": 2, "meaning": "いろ", "emoji": "🎨" },
  { "kanji": "食", "reading": { "hiragana": "たべる", "katakana": "タベル" }, "onyomi": "ショク", "grade": 2, "meaning": "たべる", "emoji": "🍴" },
  { "kanji": "心", "reading": { "hiragana": "こころ", "katakana": "ココロ" }, "onyomi": "シン", "grade": 2, "meaning": "こころ", "emoji": "❤️" },
  { "kanji": "新", "reading": { "hiragana": "あたらしい", "katakana": "アタラシイ" }, "onyomi": "シン", "grade": 2, "meaning": "あたらしい", "emoji": "🆕" },
  { "kanji": "親", "reading": { "hiragana": "おや", "katakana": "オヤ" }, "onyomi": "シン", "grade": 2, "meaning": "おや", "emoji": "👪" },
  { "kanji": "図", "reading": { "hiragana": "ず", "katakana": "ズ" }, "onyomi": "ズ", "grade": 2, "meaning": "ず", "emoji": "🗺️" },
  { "kanji": "数", "reading": { "hiragana": "かず", "katakana": "カズ" }, "onyomi": "スウ", "grade": 2, "meaning": "かず", "emoji": "🔢" },
  { "kanji": "西", "reading": { "hiragana": "にし", "katakana": "ニシ" }, "onyomi": "セイ", "grade": 2, "meaning": "にし", "emoji": "⬅️" },
  { "kanji": "声", "reading": { "hiragana": "こえ", "katakana": "コエ" }, "onyomi": "セイ", "grade": 2, "meaning": "こえ", "emoji": "🗣️" },
  { "kanji": "星", "reading": { "hiragana": "ほし", "katakana": "ホシ" }, "onyomi": "セイ", "grade": 2, "meaning": "ほし", "emoji": "⭐" },
  { "kanji": "晴", "reading": { "hiragana": "はれる", "katakana": "ハレル" }, "onyomi": "セイ", "grade": 2, "meaning": "はれる", "emoji": "☀️" },
  { "kanji": "切", "reading": { "hiragana": "きる", "katakana": "キル" }, "onyomi": "セツ", "grade": 2, "meaning": "きる", "emoji": "✂️" },
  { "kanji": "雪", "reading": { "hiragana": "ゆき", "katakana": "ユキ" }, "onyomi": "セツ", "grade": 2, "meaning": "ゆき", "emoji": "❄️" },
  { "kanji": "船", "reading": { "hiragana": "ふね", "katakana": "フネ" }, "onyomi": "セン", "grade": 2, "meaning": "ふね", "emoji": "🚢" },
  { "kanji": "線", "reading": { "hiragana": "せん", "katakana": "セン" }, "onyomi": "セン", "grade": 2, "meaning": "せん", "emoji": "➖" },
  { "kanji": "前", "reading": { "hiragana": "まえ", "katakana": "マエ" }, "onyomi": "ゼン", "grade": 2, "meaning": "まえ", "emoji": "⏮️" },
  { "kanji": "組", "reading": { "hiragana": "くむ", "katakana": "クム" }, "onyomi": "ソ", "grade": 2, "meaning": "くみ", "emoji": "👥" },
  { "kanji": "走", "reading": { "hiragana": "はしる", "katakana": "ハシル" }, "onyomi": "ソウ", "grade": 2, "meaning": "はしる", "emoji": "🏃" },
  { "kanji": "多", "reading": { "hiragana": "おおい", "katakana": "オオイ" }, "onyomi": "タ", "grade": 2, "meaning": "おおい", "emoji": "🔢" },
  { "kanji": "太", "reading": { "hiragana": "ふとい", "katakana": "フトイ" }, "onyomi": "タイ", "grade": 2, "meaning": "ふとい", "emoji": "📏" },
  { "kanji": "体", "reading": { "hiragana": "からだ", "katakana": "カラダ" }, "onyomi": "タイ", "grade": 2, "meaning": "からだ", "emoji": "💪" },
  { "kanji": "台", "reading": { "hiragana": "だい", "katakana": "ダイ" }, "onyomi": "ダイ", "grade": 2, "meaning": "だい", "emoji": "📺" },
  { "kanji": "地", "reading": { "hiragana": "ち", "katakana": "チ" }, "onyomi": "チ", "grade": 2, "meaning": "ち", "emoji": "🌍" },
  { "kanji": "池", "reading": { "hiragana": "いけ", "katakana": "イケ" }, "onyomi": "チ", "grade": 2, "meaning": "いけ", "emoji": "💧" },
  { "kanji": "知", "reading": { "hiragana": "しる", "katakana": "シル" }, "onyomi": "チ", "grade": 2, "meaning": "しる", "emoji": "🧠" },
  { "kanji": "茶", "reading": { "hiragana": "ちゃ", "katakana": "チャ" }, "onyomi": "チャ", "grade": 2, "meaning": "ちゃ", "emoji": "🍵" },
  { "kanji": "昼", "reading": { "hiragana": "ひる", "katakana": "ヒル" }, "onyomi": "チュウ", "grade": 2, "meaning": "ひる", "emoji": "🌞" },
  { "kanji": "長", "reading": { "hiragana": "ながい", "katakana": "ナガイ" }, "onyomi": "チョウ", "grade": 2, "meaning": "ながい", "emoji": "📏" },
  { "kanji": "鳥", "reading": { "hiragana": "とり", "katakana": "トリ" }, "onyomi": "チョウ", "grade": 2, "meaning": "とり", "emoji": "🐦" },
  { "kanji": "朝", "reading": { "hiragana": "あさ", "katakana": "アサ" }, "onyomi": "チョウ", "grade": 2, "meaning": "あさ", "emoji": "🌅" },
  { "kanji": "通", "reading": { "hiragana": "とおる", "katakana": "トオル" }, "onyomi": "ツウ", "grade": 2, "meaning": "とおる", "emoji": "🚶" },
  { "kanji": "弟", "reading": { "hiragana": "おとうと", "katakana": "オトウト" }, "onyomi": "テイ", "grade": 2, "meaning": "おとうと", "emoji": "👦" },
  { "kanji": "店", "reading": { "hiragana": "みせ", "katakana": "ミセ" }, "onyomi": "テン", "grade": 2, "meaning": "みせ", "emoji": "🏪" },
  { "kanji": "点", "reading": { "hiragana": "てん", "katakana": "テン" }, "onyomi": "テン", "grade": 2, "meaning": "てん", "emoji": "🔵" },
  { "kanji": "電", "reading": { "hiragana": "でん", "katakana": "デン" }, "onyomi": "デン", "grade": 2, "meaning": "でんき", "emoji": "⚡" },
  { "kanji": "冬", "reading": { "hiragana": "ふゆ", "katakana": "フユ" }, "onyomi": "トウ", "grade": 2, "meaning": "ふゆ", "emoji": "❄️" },
  { "kanji": "刀", "reading": { "hiragana": "かたな", "katakana": "カタナ" }, "onyomi": "トウ", "grade": 2, "meaning": "かたな", "emoji": "⚔️" },
  { "kanji": "東", "reading": { "hiragana": "ひがし", "katakana": "ヒガシ" }, "onyomi": "トウ", "grade": 2, "meaning": "ひがし", "emoji": "➡️" },
  { "kanji": "当", "reading": { "hiragana": "あたる", "katakana": "アタル" }, "onyomi": "トウ", "grade": 2, "meaning": "あたる", "emoji": "🎯" },
  { "kanji": "答", "reading": { "hiragana": "こたえる", "katakana": "コタエル" }, "onyomi": "トウ", "grade": 2, "meaning": "こたえる", "emoji": "💬" },
  { "kanji": "頭", "reading": { "hiragana": "あたま", "katakana": "アタマ" }, "onyomi": "トウ", "grade": 2, "meaning": "あたま", "emoji": "👤" },
  { "kanji": "同", "reading": { "hiragana": "おなじ", "katakana": "オナジ" }, "onyomi": "ドウ", "grade": 2, "meaning": "おなじ", "emoji": "🔄" },
  { "kanji": "道", "reading": { "hiragana": "みち", "katakana": "ミチ" }, "onyomi": "ドウ", "grade": 2, "meaning": "みち", "emoji": "🛣️" },
  { "kanji": "読", "reading": { "hiragana": "よむ", "katakana": "ヨム" }, "onyomi": "ドク", "grade": 2, "meaning": "よむ", "emoji": "📖" },
  { "kanji": "南", "reading": { "hiragana": "みなみ", "katakana": "ミナミ" }, "onyomi": "ナン", "grade": 2, "meaning": "みなみ", "emoji": "⬇️" },
  { "kanji": "肉", "reading": { "hiragana": "にく", "katakana": "ニク" }, "onyomi": "ニク", "grade": 2, "meaning": "にく", "emoji": "🍖" },
  { "kanji": "馬", "reading": { "hiragana": "うま", "katakana": "ウマ" }, "onyomi": "バ", "grade": 2, "meaning": "うま", "emoji": "🐎" },
  { "kanji": "売", "reading": { "hiragana": "うる", "katakana": "ウル" }, "onyomi": "バイ", "grade": 2, "meaning": "うる", "emoji": "💰" },
  { "kanji": "買", "reading": { "hiragana": "かう", "katakana": "カウ" }, "onyomi": "バイ", "grade": 2, "meaning": "かう", "emoji": "🛒" },
  { "kanji": "麦", "reading": { "hiragana": "むぎ", "katakana": "ムギ" }, "onyomi": "バク", "grade": 2, "meaning": "むぎ", "emoji": "🌾" },
  { "kanji": "半", "reading": { "hiragana": "はん", "katakana": "ハン" }, "onyomi": "ハン", "grade": 2, "meaning": "はん", "emoji": "½" },
  { "kanji": "番", "reading": { "hiragana": "ばん", "katakana": "バン" }, "onyomi": "バン", "grade": 2, "meaning": "ばん", "emoji": "#️⃣" },
  { "kanji": "父", "reading": { "hiragana": "ちち", "katakana": "チチ" }, "onyomi": "フ", "grade": 2, "meaning": "ちち", "emoji": "👨" },
  { "kanji": "風", "reading": { "hiragana": "かぜ", "katakana": "カゼ" }, "onyomi": "フウ", "grade": 2, "meaning": "かぜ", "emoji": "🌬️" },
  { "kanji": "分", "reading": { "hiragana": "わかる", "katakana": "ワカル" }, "onyomi": "ブン", "grade": 2, "meaning": "わかる", "emoji": "⏱️" },
  { "kanji": "聞", "reading": { "hiragana": "きく", "katakana": "キク" }, "onyomi": "ブン", "grade": 2, "meaning": "きく", "emoji": "👂" },
  { "kanji": "米", "reading": { "hiragana": "こめ", "katakana": "コメ" }, "onyomi": "マイ", "grade": 2, "meaning": "こめ", "emoji": "🍚" },
  { "kanji": "歩", "reading": { "hiragana": "あるく", "katakana": "アルク" }, "onyomi": "ホ", "grade": 2, "meaning": "あるく", "emoji": "🚶" },
  { "kanji": "母", "reading": { "hiragana": "はは", "katakana": "ハハ" }, "onyomi": "ボ", "grade": 2, "meaning": "はは", "emoji": "👩" },
  { "kanji": "方", "reading": { "hiragana": "ほう", "katakana": "ホウ" }, "onyomi": "ホウ", "grade": 2, "meaning": "ほう", "emoji": "🧭" },
  { "kanji": "北", "reading": { "hiragana": "きた", "katakana": "キタ" }, "onyomi": "ホク", "grade": 2, "meaning": "きた", "emoji": "⬆️" },
  { "kanji": "毎", "reading": { "hiragana": "まい", "katakana": "マイ" }, "onyomi": "マイ", "grade": 2, "meaning": "まい", "emoji": "🔄" },
  { "kanji": "妹", "reading": { "hiragana": "いもうと", "katakana": "イモウト" }, "onyomi": "マイ", "grade": 2, "meaning": "いもうと", "emoji": "👧" },
  { "kanji": "万", "reading": { "hiragana": "まん", "katakana": "マン" }, "onyomi": "マン", "grade": 2, "meaning": "まん", "emoji": "🔢" },
  { "kanji": "明", "reading": { "hiragana": "あかるい", "katakana": "アカルイ" }, "onyomi": "メイ", "grade": 2, "meaning": "あかるい", "emoji": "💡" },
  { "kanji": "鳴", "reading": { "hiragana": "なく", "katakana": "ナク" }, "onyomi": "メイ", "grade": 2, "meaning": "なく", "emoji": "🐦" },
  { "kanji": "毛", "reading": { "hiragana": "け", "katakana": "ケ" }, "onyomi": "モウ", "grade": 2, "meaning": "け", "emoji": "🧶" },
  { "kanji": "門", "reading": { "hiragana": "もん", "katakana": "モン" }, "onyomi": "モン", "grade": 2, "meaning": "もん", "emoji": "🚪" },
  { "kanji": "夜", "reading": { "hiragana": "よる", "katakana": "ヨル" }, "onyomi": "ヤ", "grade": 2, "meaning": "よる", "emoji": "🌙" },
  { "kanji": "野", "reading": { "hiragana": "の", "katakana": "ノ" }, "onyomi": "ヤ", "grade": 2, "meaning": "の", "emoji": "🌾" },
  { "kanji": "友", "reading": { "hiragana": "とも", "katakana": "トモ" }, "onyomi": "ユウ", "grade": 2, "meaning": "とも", "emoji": "👫" },
  { "kanji": "用", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 2, "meaning": "よう", "emoji": "🛠️" },
  { "kanji": "曜", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 2, "meaning": "よう", "emoji": "📅" },
  { "kanji": "来", "reading": { "hiragana": "くる", "katakana": "クル" }, "onyomi": "ライ", "grade": 2, "meaning": "くる", "emoji": "➡️" },
  { "kanji": "里", "reading": { "hiragana": "さと", "katakana": "サト" }, "onyomi": "リ", "grade": 2, "meaning": "さと", "emoji": "🏘️" },
  { "kanji": "理", "reading": { "hiragana": "り", "katakana": "リ" }, "onyomi": "リ", "grade": 2, "meaning": "り", "emoji": "🧠" },
  { "kanji": "話", "reading": { "hiragana": "はなす", "katakana": "ハナス" }, "onyomi": "ワ", "grade": 2, "meaning": "はなし", "emoji": "🗣️" },
  { "kanji": "丁", "reading": { "hiragana": "てい", "katakana": "テイ" }, "onyomi": "テイ", "grade": 3, "meaning": "ひのと（えと）", "emoji": "🔲" },
  { "kanji": "世", "reading": { "hiragana": "せ", "katakana": "セ" }, "onyomi": "セ", "grade": 3, "meaning": "よ", "emoji": "🌍" },
  { "kanji": "両", "reading": { "hiragana": "りょう", "katakana": "リョウ" }, "onyomi": "リョウ", "grade": 3, "meaning": "ふたつ", "emoji": "⚖️" },
  { "kanji": "主", "reading": { "hiragana": "しゅ", "katakana": "シュ" }, "onyomi": "シュ", "grade": 3, "meaning": "おも", "emoji": "👑" },
  { "kanji": "乗", "reading": { "hiragana": "じょう", "katakana": "ジョウ" }, "onyomi": "ジョウ", "grade": 3, "meaning": "のる", "emoji": "🚂" },
  { "kanji": "予", "reading": { "hiragana": "よ", "katakana": "ヨ" }, "onyomi": "ヨ", "grade": 3, "meaning": "あらかじめ", "emoji": "⏳" },
  { "kanji": "事", "reading": { "hiragana": "じ", "katakana": "ジ" }, "onyomi": "ジ", "grade": 3, "meaning": "こと", "emoji": "📝" },
  { "kanji": "仕", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 3, "meaning": "つかえる", "emoji": "💼" },
  { "kanji": "他", "reading": { "hiragana": "た", "katakana": "タ" }, "onyomi": "タ", "grade": 3, "meaning": "ほか", "emoji": "👥" },
  { "kanji": "代", "reading": { "hiragana": "だい", "katakana": "ダイ" }, "onyomi": "ダイ", "grade": 3, "meaning": "かわる", "emoji": "🔄" },
  { "kanji": "住", "reading": { "hiragana": "じゅう", "katakana": "ジュウ" }, "onyomi": "ジュウ", "grade": 3, "meaning": "すむ", "emoji": "🏠" },
  { "kanji": "使", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 3, "meaning": "つかう", "emoji": "🛠️" },
  { "kanji": "係", "reading": { "hiragana": "けい", "katakana": "ケイ" }, "onyomi": "ケイ", "grade": 3, "meaning": "かかり", "emoji": "🧑‍💼" },
  { "kanji": "倍", "reading": { "hiragana": "ばい", "katakana": "バイ" }, "onyomi": "バイ", "grade": 3, "meaning": "ふえる", "emoji": "✖️" },
  { "kanji": "全", "reading": { "hiragana": "ぜん", "katakana": "ゼン" }, "onyomi": "ゼン", "grade": 3, "meaning": "すべて", "emoji": "🌐" },
  { "kanji": "具", "reading": { "hiragana": "ぐ", "katakana": "グ" }, "onyomi": "グ", "grade": 3, "meaning": "そなえる", "emoji": "🧰" },
  { "kanji": "写", "reading": { "hiragana": "しゃ", "katakana": "シャ" }, "onyomi": "シャ", "grade": 3, "meaning": "うつす", "emoji": "📷" },
  { "kanji": "列", "reading": { "hiragana": "れつ", "katakana": "レツ" }, "onyomi": "レツ", "grade": 3, "meaning": "ならぶ", "emoji": "🚂" },
  { "kanji": "助", "reading": { "hiragana": "じょ", "katakana": "ジョ" }, "onyomi": "ジョ", "grade": 3, "meaning": "たすける", "emoji": "🤝" },
  { "kanji": "勉", "reading": { "hiragana": "べん", "katakana": "ベン" }, "onyomi": "ベン", "grade": 3, "meaning": "べんきょう", "emoji": "📚" },
  { "kanji": "動", "reading": { "hiragana": "どう", "katakana": "ドウ" }, "onyomi": "ドウ", "grade": 3, "meaning": "うごく", "emoji": "🏃" },
  { "kanji": "勝", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 3, "meaning": "かつ", "emoji": "🏆" },
  { "kanji": "化", "reading": { "hiragana": "か", "katakana": "カ" }, "onyomi": "カ", "grade": 3, "meaning": "ばける", "emoji": "🦋" },
  { "kanji": "区", "reading": { "hiragana": "く", "katakana": "ク" }, "onyomi": "ク", "grade": 3, "meaning": "わける", "emoji": "📍" },
  { "kanji": "医", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 3, "meaning": "いしゃ", "emoji": "⚕️" },
  { "kanji": "去", "reading": { "hiragana": "きょ", "katakana": "キョ" }, "onyomi": "キョ", "grade": 3, "meaning": "さる", "emoji": "👋" },
  { "kanji": "反", "reading": { "hiragana": "はん", "katakana": "ハン" }, "onyomi": "ハン", "grade": 3, "meaning": "そむく", "emoji": "🔄" },
  { "kanji": "取", "reading": { "hiragana": "しゅ", "katakana": "シュ" }, "onyomi": "シュ", "grade": 3, "meaning": "とる", "emoji": "✋" },
  { "kanji": "受", "reading": { "hiragana": "じゅ", "katakana": "ジュ" }, "onyomi": "ジュ", "grade": 3, "meaning": "うける", "emoji": "🤲" },
  { "kanji": "号", "reading": { "hiragana": "ごう", "katakana": "ゴウ" }, "onyomi": "ゴウ", "grade": 3, "meaning": "ばんごう", "emoji": "🔢" },
  { "kanji": "向", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 3, "meaning": "むく", "emoji": "➡️" },
  { "kanji": "君", "reading": { "hiragana": "くん", "katakana": "クン" }, "onyomi": "クン", "grade": 3, "meaning": "きみ", "emoji": "👑" },
  { "kanji": "味", "reading": { "hiragana": "み", "katakana": "ミ" }, "onyomi": "ミ", "grade": 3, "meaning": "あじ", "emoji": "👅" },
  { "kanji": "命", "reading": { "hiragana": "めい", "katakana": "メイ" }, "onyomi": "メイ", "grade": 3, "meaning": "いのち", "emoji": "❤️" },
  { "kanji": "和", "reading": { "hiragana": "わ", "katakana": "ワ" }, "onyomi": "ワ", "grade": 3, "meaning": "やわらぐ", "emoji": "🕊️" },
  { "kanji": "品", "reading": { "hiragana": "ひん", "katakana": "ヒン" }, "onyomi": "ヒン", "grade": 3, "meaning": "しな", "emoji": "📦" },
  { "kanji": "員", "reading": { "hiragana": "いん", "katakana": "イン" }, "onyomi": "イン", "grade": 3, "meaning": "かず", "emoji": "👥" },
  { "kanji": "商", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 3, "meaning": "あきなう", "emoji": "💰" },
  { "kanji": "問", "reading": { "hiragana": "もん", "katakana": "モン" }, "onyomi": "モン", "grade": 3, "meaning": "とう", "emoji": "❓" },
  { "kanji": "坂", "reading": { "hiragana": "はん", "katakana": "ハン" }, "onyomi": "ハン", "grade": 3, "meaning": "さか", "emoji": "⛰️" },
  { "kanji": "央", "reading": { "hiragana": "おう", "katakana": "オウ" }, "onyomi": "オウ", "grade": 3, "meaning": "まんなか", "emoji": "🎯" },
  { "kanji": "始", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 3, "meaning": "はじめる", "emoji": "⏳" },
  { "kanji": "委", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 3, "meaning": "ゆだねる", "emoji": "📋" },
  { "kanji": "守", "reading": { "hiragana": "しゅ", "katakana": "シュ" }, "onyomi": "シュ", "grade": 3, "meaning": "まもる", "emoji": "🛡️" },
  { "kanji": "安", "reading": { "hiragana": "あん", "katakana": "アン" }, "onyomi": "アン", "grade": 3, "meaning": "やすい", "emoji": "🛌" },
  { "kanji": "定", "reading": { "hiragana": "てい", "katakana": "テイ" }, "onyomi": "テイ", "grade": 3, "meaning": "さだめる", "emoji": "⏲️" },
  { "kanji": "実", "reading": { "hiragana": "じつ", "katakana": "ジツ" }, "onyomi": "ジツ", "grade": 3, "meaning": "み", "emoji": "🍎" },
  { "kanji": "客", "reading": { "hiragana": "きゃく", "katakana": "キャク" }, "onyomi": "キャク", "grade": 3, "meaning": "おきゃく", "emoji": "👤" },
  { "kanji": "宮", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 3, "meaning": "みや", "emoji": "⛩️" },
  { "kanji": "宿", "reading": { "hiragana": "しゅく", "katakana": "シュク" }, "onyomi": "シュク", "grade": 3, "meaning": "やど", "emoji": "🏨" },
  { "kanji": "寒", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 3, "meaning": "さむい", "emoji": "❄️" },
  { "kanji": "対", "reading": { "hiragana": "たい", "katakana": "タイ" }, "onyomi": "タイ", "grade": 3, "meaning": "むかう", "emoji": "⚔️" },
  { "kanji": "局", "reading": { "hiragana": "きょく", "katakana": "キョク" }, "onyomi": "キョク", "grade": 3, "meaning": "つぼね", "emoji": "🏢" },
  { "kanji": "屋", "reading": { "hiragana": "おく", "katakana": "オク" }, "onyomi": "オク", "grade": 3, "meaning": "や", "emoji": "🏠" },
  { "kanji": "岸", "reading": { "hiragana": "がん", "katakana": "ガン" }, "onyomi": "ガン", "grade": 3, "meaning": "きし", "emoji": "🌊" },
  { "kanji": "島", "reading": { "hiragana": "とう", "katakana": "トウ" }, "onyomi": "トウ", "grade": 3, "meaning": "しま", "emoji": "🏝️" },
  { "kanji": "州", "reading": { "hiragana": "しゅう", "katakana": "シュウ" }, "onyomi": "シュウ", "grade": 3, "meaning": "す", "emoji": "🗾" },
  { "kanji": "帳", "reading": { "hiragana": "ちょう", "katakana": "チョウ" }, "onyomi": "チョウ", "grade": 3, "meaning": "とばり", "emoji": "📒" },
  { "kanji": "平", "reading": { "hiragana": "へい", "katakana": "ヘイ" }, "onyomi": "ヘイ", "grade": 3, "meaning": "たいら", "emoji": "⚖️" },
  { "kanji": "幸", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 3, "meaning": "しあわせ", "emoji": "🍀" },
  { "kanji": "度", "reading": { "hiragana": "ど", "katakana": "ド" }, "onyomi": "ド", "grade": 3, "meaning": "たび", "emoji": "🌡️" },
  { "kanji": "庫", "reading": { "hiragana": "こ", "katakana": "コ" }, "onyomi": "コ", "grade": 3, "meaning": "くら", "emoji": "🏚️" },
  { "kanji": "庭", "reading": { "hiragana": "てい", "katakana": "テイ" }, "onyomi": "テイ", "grade": 3, "meaning": "にわ", "emoji": "🌳" },
  { "kanji": "式", "reading": { "hiragana": "しき", "katakana": "シキ" }, "onyomi": "シキ", "grade": 3, "meaning": "のり", "emoji": "📐" },
  { "kanji": "役", "reading": { "hiragana": "やく", "katakana": "ヤク" }, "onyomi": "ヤク", "grade": 3, "meaning": "えき", "emoji": "🎭" },
  { "kanji": "待", "reading": { "hiragana": "たい", "katakana": "タイ" }, "onyomi": "タイ", "grade": 3, "meaning": "まつ", "emoji": "⏳" },
  { "kanji": "急", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 3, "meaning": "いそぐ", "emoji": "🚨" },
  { "kanji": "息", "reading": { "hiragana": "そく", "katakana": "ソク" }, "onyomi": "ソク", "grade": 3, "meaning": "いき", "emoji": "💨" },
  { "kanji": "悪", "reading": { "hiragana": "あく", "katakana": "アク" }, "onyomi": "アク", "grade": 3, "meaning": "わるい", "emoji": "👿" },
  { "kanji": "悲", "reading": { "hiragana": "ひ", "katakana": "ヒ" }, "onyomi": "ヒ", "grade": 3, "meaning": "かなしい", "emoji": "😢" },
  { "kanji": "想", "reading": { "hiragana": "そう", "katakana": "ソウ" }, "onyomi": "ソウ", "grade": 3, "meaning": "おもう", "emoji": "💭" },
  { "kanji": "意", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 3, "meaning": "こころ", "emoji": "💡" },
  { "kanji": "戦", "reading": { "hiragana": "せん", "katakana": "セン" }, "onyomi": "セン", "grade": 3, "meaning": "たたかう", "emoji": "⚔️" },
  { "kanji": "所", "reading": { "hiragana": "しょ", "katakana": "ショ" }, "onyomi": "ショ", "grade": 3, "meaning": "ところ", "emoji": "📍" },
  { "kanji": "打", "reading": { "hiragana": "だ", "katakana": "ダ" }, "onyomi": "ダ", "grade": 3, "meaning": "うつ", "emoji": "👊" },
  { "kanji": "投", "reading": { "hiragana": "とう", "katakana": "トウ" }, "onyomi": "トウ", "grade": 3, "meaning": "なげる", "emoji": "⚾" },
  { "kanji": "拾", "reading": { "hiragana": "しゅう", "katakana": "シュウ" }, "onyomi": "シュウ", "grade": 3, "meaning": "ひろう", "emoji": "🖐️" },
  { "kanji": "持", "reading": { "hiragana": "じ", "katakana": "ジ" }, "onyomi": "ジ", "grade": 3, "meaning": "もつ", "emoji": "🤲" },
  { "kanji": "指", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 3, "meaning": "ゆび", "emoji": "👉" },
  { "kanji": "放", "reading": { "hiragana": "ほう", "katakana": "ホウ" }, "onyomi": "ホウ", "grade": 3, "meaning": "はなす", "emoji": "🕊️" },
  { "kanji": "整", "reading": { "hiragana": "せい", "katakana": "セイ" }, "onyomi": "セイ", "grade": 3, "meaning": "ととのえる", "emoji": "🧹" },
  { "kanji": "旅", "reading": { "hiragana": "りょ", "katakana": "リョ" }, "onyomi": "リョ", "grade": 3, "meaning": "たび", "emoji": "✈️" },
  { "kanji": "族", "reading": { "hiragana": "ぞく", "katakana": "ゾク" }, "onyomi": "ゾク", "grade": 3, "meaning": "やから", "emoji": "👨‍👩‍👧‍👦" },
  { "kanji": "昔", "reading": { "hiragana": "せき", "katakana": "セキ" }, "onyomi": "セキ", "grade": 3, "meaning": "むかし", "emoji": "⏳" },
  { "kanji": "昭", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 3, "meaning": "あきらか", "emoji": "☀️" },
  { "kanji": "暑", "reading": { "hiragana": "しょ", "katakana": "ショ" }, "onyomi": "ショ", "grade": 3, "meaning": "あつい", "emoji": "🔥" },
  { "kanji": "暗", "reading": { "hiragana": "あん", "katakana": "アン" }, "onyomi": "アン", "grade": 3, "meaning": "くらい", "emoji": "🌑" },
  { "kanji": "曲", "reading": { "hiragana": "きょく", "katakana": "キョク" }, "onyomi": "キョク", "grade": 3, "meaning": "まがる", "emoji": "🎵" },
  { "kanji": "有", "reading": { "hiragana": "ゆう", "katakana": "ユウ" }, "onyomi": "ユウ", "grade": 3, "meaning": "ある", "emoji": "🈶" },
  { "kanji": "服", "reading": { "hiragana": "ふく", "katakana": "フク" }, "onyomi": "フク", "grade": 3, "meaning": "きる", "emoji": "👕" },
  { "kanji": "期", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 3, "meaning": "とき", "emoji": "🗓️" },
  { "kanji": "板", "reading": { "hiragana": "ばん", "katakana": "バン" }, "onyomi": "バン", "grade": 3, "meaning": "いた", "emoji": "📏" },
  { "kanji": "柱", "reading": { "hiragana": "ちゅう", "katakana": "チュウ" }, "onyomi": "チュウ", "grade": 3, "meaning": "はしら", "emoji": "🏛️" },
  { "kanji": "根", "reading": { "hiragana": "こん", "katakana": "コン" }, "onyomi": "コン", "grade": 3, "meaning": "ね", "emoji": "🌱" },
  { "kanji": "植", "reading": { "hiragana": "しょく", "katakana": "ショク" }, "onyomi": "ショク", "grade": 3, "meaning": "うえる", "emoji": "🌱" },
  { "kanji": "業", "reading": { "hiragana": "ぎょう", "katakana": "ギョウ" }, "onyomi": "ギョウ", "grade": 3, "meaning": "わざ", "emoji": "🏢" },
  { "kanji": "様", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 3, "meaning": "さま", "emoji": "🙇" },
  { "kanji": "横", "reading": { "hiragana": "おう", "katakana": "オウ" }, "onyomi": "オウ", "grade": 3, "meaning": "よこ", "emoji": "↔️" },
  { "kanji": "橋", "reading": { "hiragana": "きょう", "katakana": "キョウ" }, "onyomi": "キョウ", "grade": 3, "meaning": "はし", "emoji": "🌉" },
  { "kanji": "次", "reading": { "hiragana": "じ", "katakana": "ジ" }, "onyomi": "ジ", "grade": 3, "meaning": "つぎ", "emoji": "⏭️" },
  { "kanji": "歯", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 3, "meaning": "は", "emoji": "🦷" },
  { "kanji": "死", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 3, "meaning": "しぬ", "emoji": "💀" },
  { "kanji": "氷", "reading": { "hiragana": "ひょう", "katakana": "ヒョウ" }, "onyomi": "ヒョウ", "grade": 3, "meaning": "こおり", "emoji": "🧊" },
  { "kanji": "決", "reading": { "hiragana": "けつ", "katakana": "ケツ" }, "onyomi": "ケツ", "grade": 3, "meaning": "きめる", "emoji": "✅" },
  { "kanji": "油", "reading": { "hiragana": "ゆ", "katakana": "ユ" }, "onyomi": "ユ", "grade": 3, "meaning": "あぶら", "emoji": "🛢️" },
  { "kanji": "波", "reading": { "hiragana": "は", "katakana": "ハ" }, "onyomi": "ハ", "grade": 3, "meaning": "なみ", "emoji": "🌊" },
  { "kanji": "注", "reading": { "hiragana": "ちゅう", "katakana": "チュウ" }, "onyomi": "チュウ", "grade": 3, "meaning": "そそぐ", "emoji": "💧" },
  { "kanji": "泳", "reading": { "hiragana": "えい", "katakana": "エイ" }, "onyomi": "エイ", "grade": 3, "meaning": "およぐ", "emoji": "🏊" },
  { "kanji": "洋", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 3, "meaning": "うみ", "emoji": "🌊" },
  { "kanji": "流", "reading": { "hiragana": "りゅう", "katakana": "リュウ" }, "onyomi": "リュウ", "grade": 3, "meaning": "ながれる", "emoji": "🌊" },
  { "kanji": "消", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 3, "meaning": "きえる", "emoji": "🧯" },
  { "kanji": "深", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 3, "meaning": "ふかい", "emoji": "🕳️" },
  { "kanji": "温", "reading": { "hiragana": "おん", "katakana": "オン" }, "onyomi": "オン", "grade": 3, "meaning": "あたたかい", "emoji": "☀️" },
  { "kanji": "港", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 3, "meaning": "みなと", "emoji": "⚓" },
  { "kanji": "湖", "reading": { "hiragana": "こ", "katakana": "コ" }, "onyomi": "コ", "grade": 3, "meaning": "みずうみ", "emoji": "🏞️" },
  { "kanji": "湯", "reading": { "hiragana": "とう", "katakana": "トウ" }, "onyomi": "トウ", "grade": 3, "meaning": "ゆ", "emoji": "♨️" },
  { "kanji": "漢", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 3, "meaning": "から", "emoji": "🀄" },
  { "kanji": "炭", "reading": { "hiragana": "たん", "katakana": "タン" }, "onyomi": "タン", "grade": 3, "meaning": "すみ", "emoji": "🔥" },
  { "kanji": "物", "reading": { "hiragana": "ぶつ", "katakana": "ブツ" }, "onyomi": "ブツ", "grade": 3, "meaning": "もの", "emoji": "📦" },
  { "kanji": "球", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 3, "meaning": "たま", "emoji": "⚽" },
  { "kanji": "由", "reading": { "hiragana": "ゆ", "katakana": "ユ" }, "onyomi": "ユ", "grade": 3, "meaning": "よし", "emoji": "🛤️" },
  { "kanji": "申", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 3, "meaning": "もうす", "emoji": "🙏" },
  { "kanji": "界", "reading": { "hiragana": "かい", "katakana": "カイ" }, "onyomi": "カイ", "grade": 3, "meaning": "さかい", "emoji": "🌐" },
  { "kanji": "畑", "reading": { "hiragana": "はた", "katakana": "ハタ" }, "onyomi": "ハタ", "grade": 3, "meaning": "はたけ", "emoji": "🌾" },
  { "kanji": "病", "reading": { "hiragana": "びょう", "katakana": "ビョウ" }, "onyomi": "ビョウ", "grade": 3, "meaning": "やまい", "emoji": "🏥" },
  { "kanji": "発", "reading": { "hiragana": "はつ", "katakana": "ハツ" }, "onyomi": "ハツ", "grade": 3, "meaning": "あばく", "emoji": "🚀" },
  { "kanji": "登", "reading": { "hiragana": "とう", "katakana": "トウ" }, "onyomi": "トウ", "grade": 3, "meaning": "のぼる", "emoji": "🧗" },
  { "kanji": "皮", "reading": { "hiragana": "ひ", "katakana": "ヒ" }, "onyomi": "ヒ", "grade": 3, "meaning": "かわ", "emoji": "🍎" },
  { "kanji": "皿", "reading": { "hiragana": "さら", "katakana": "サラ" }, "onyomi": "サラ", "grade": 3, "meaning": "さら", "emoji": "🍽️" },
  { "kanji": "相", "reading": { "hiragana": "そう", "katakana": "ソウ" }, "onyomi": "ソウ", "grade": 3, "meaning": "あい", "emoji": "🤝" },
  { "kanji": "県", "reading": { "hiragana": "けん", "katakana": "ケン" }, "onyomi": "ケン", "grade": 3, "meaning": "あがた", "emoji": "🗾" },
  { "kanji": "真", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 3, "meaning": "ま", "emoji": "✨" },
  { "kanji": "着", "reading": { "hiragana": "ちゃく", "katakana": "チャク" }, "onyomi": "チャク", "grade": 3, "meaning": "きる", "emoji": "👕" },
  { "kanji": "短", "reading": { "hiragana": "たん", "katakana": "タン" }, "onyomi": "タン", "grade": 3, "meaning": "みじかい", "emoji": "📏" },
  { "kanji": "研", "reading": { "hiragana": "けん", "katakana": "ケン" }, "onyomi": "ケン", "grade": 3, "meaning": "とぐ", "emoji": "🔬" },
  { "kanji": "礼", "reading": { "hiragana": "れい", "katakana": "レイ" }, "onyomi": "レイ", "grade": 3, "meaning": "れい", "emoji": "🙇" },
  { "kanji": "神", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 3, "meaning": "かみ", "emoji": "⛩️" },
  { "kanji": "祭", "reading": { "hiragana": "さい", "katakana": "サイ" }, "onyomi": "サイ", "grade": 3, "meaning": "まつる", "emoji": "🎉" },
  { "kanji": "福", "reading": { "hiragana": "ふく", "katakana": "フク" }, "onyomi": "フク", "grade": 3, "meaning": "さいわい", "emoji": "🍀" },
  { "kanji": "秒", "reading": { "hiragana": "びょう", "katakana": "ビョウ" }, "onyomi": "ビョウ", "grade": 3, "meaning": "びょう", "emoji": "⏱️" },
  { "kanji": "究", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 3, "meaning": "きわめる", "emoji": "🔍" },
  { "kanji": "章", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 3, "meaning": "あや", "emoji": "📜" },
  { "kanji": "童", "reading": { "hiragana": "どう", "katakana": "ドウ" }, "onyomi": "ドウ", "grade": 3, "meaning": "わらべ", "emoji": "🧒" },
  { "kanji": "笛", "reading": { "hiragana": "てき", "katakana": "テキ" }, "onyomi": "テキ", "grade": 3, "meaning": "ふえ", "emoji": "🎶" },
  { "kanji": "第", "reading": { "hiragana": "だい", "katakana": "ダイ" }, "onyomi": "ダイ", "grade": 3, "meaning": "ついで", "emoji": "1️⃣" },
  { "kanji": "筆", "reading": { "hiragana": "ひつ", "katakana": "ヒツ" }, "onyomi": "ヒツ", "grade": 3, "meaning": "ふで", "emoji": "🖌️" },
  { "kanji": "等", "reading": { "hiragana": "とう", "katakana": "トウ" }, "onyomi": "トウ", "grade": 3, "meaning": "ひとしい", "emoji": "⚖️" },
  { "kanji": "箱", "reading": { "hiragana": "はこ", "katakana": "ハコ" }, "onyomi": "ハコ", "grade": 3, "meaning": "はこ", "emoji": "📦" },
  { "kanji": "級", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 3, "meaning": "ぐらい", "emoji": "📊" },
  { "kanji": "終", "reading": { "hiragana": "しゅう", "katakana": "シュウ" }, "onyomi": "シュウ", "grade": 3, "meaning": "おわる", "emoji": "🔚" },
  { "kanji": "緑", "reading": { "hiragana": "りょく", "katakana": "リョク" }, "onyomi": "リョク", "grade": 3, "meaning": "みどり", "emoji": "💚" },
  { "kanji": "練", "reading": { "hiragana": "れん", "katakana": "レン" }, "onyomi": "レン", "grade": 3, "meaning": "ねる", "emoji": "🧵" },
  { "kanji": "羊", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 3, "meaning": "ひつじ", "emoji": "🐑" },
  { "kanji": "美", "reading": { "hiragana": "び", "katakana": "ビ" }, "onyomi": "ビ", "grade": 3, "meaning": "うつくしい", "emoji": "✨" },
  { "kanji": "習", "reading": { "hiragana": "しゅう", "katakana": "シュウ" }, "onyomi": "シュウ", "grade": 3, "meaning": "ならう", "emoji": "📖" },
  { "kanji": "者", "reading": { "hiragana": "しゃ", "katakana": "シャ" }, "onyomi": "シャ", "grade": 3, "meaning": "もの", "emoji": "👤" },
  { "kanji": "育", "reading": { "hiragana": "いく", "katakana": "イク" }, "onyomi": "イク", "grade": 3, "meaning": "そだつ", "emoji": "🌱" },
  { "kanji": "苦", "reading": { "hiragana": "く", "katakana": "ク" }, "onyomi": "ク", "grade": 3, "meaning": "くるしい", "emoji": "😖" },
  { "kanji": "荷", "reading": { "hiragana": "か", "katakana": "カ" }, "onyomi": "カ", "grade": 3, "meaning": "に", "emoji": "🎒" },
  { "kanji": "落", "reading": { "hiragana": "らく", "katakana": "ラク" }, "onyomi": "ラク", "grade": 3, "meaning": "おちる", "emoji": "🍂" },
  { "kanji": "葉", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 3, "meaning": "は", "emoji": "🍃" },
  { "kanji": "薬", "reading": { "hiragana": "やく", "katakana": "ヤク" }, "onyomi": "ヤク", "grade": 3, "meaning": "くすり", "emoji": "💊" },
  { "kanji": "血", "reading": { "hiragana": "けつ", "katakana": "ケツ" }, "onyomi": "ケツ", "grade": 3, "meaning": "ち", "emoji": "🩸" },
  { "kanji": "表", "reading": { "hiragana": "ひょう", "katakana": "ヒョウ" }, "onyomi": "ヒョウ", "grade": 3, "meaning": "おもて", "emoji": "📊" },
  { "kanji": "詩", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 3, "meaning": "うた", "emoji": "📜" },
  { "kanji": "調", "reading": { "hiragana": "ちょう", "katakana": "チョウ" }, "onyomi": "チョウ", "grade": 3, "meaning": "しらべる", "emoji": "🔍" },
  { "kanji": "談", "reading": { "hiragana": "だん", "katakana": "ダン" }, "onyomi": "ダン", "grade": 3, "meaning": "はなし", "emoji": "💬" },
  { "kanji": "豆", "reading": { "hiragana": "とう", "katakana": "トウ" }, "onyomi": "トウ", "grade": 3, "meaning": "まめ", "emoji": "🫘" },
  { "kanji": "負", "reading": { "hiragana": "ふ", "katakana": "フ" }, "onyomi": "フ", "grade": 3, "meaning": "まける", "emoji": "😞" },
  { "kanji": "起", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 3, "meaning": "おきる", "emoji": "⏰" },
  { "kanji": "路", "reading": { "hiragana": "ろ", "katakana": "ロ" }, "onyomi": "ロ", "grade": 3, "meaning": "みち", "emoji": "🛣️" },
  { "kanji": "身", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 3, "meaning": "み", "emoji": "🧍" },
  { "kanji": "転", "reading": { "hiragana": "てん", "katakana": "テン" }, "onyomi": "テン", "grade": 3, "meaning": "ころがる", "emoji": "🔄" },
  { "kanji": "軽", "reading": { "hiragana": "けい", "katakana": "ケイ" }, "onyomi": "ケイ", "grade": 3, "meaning": "かるい", "emoji": "🪶" },
  { "kanji": "農", "reading": { "hiragana": "のう", "katakana": "ノウ" }, "onyomi": "ノウ", "grade": 3, "meaning": "のう", "emoji": "🚜" },
  { "kanji": "返", "reading": { "hiragana": "へん", "katakana": "ヘン" }, "onyomi": "ヘン", "grade": 3, "meaning": "かえす", "emoji": "🔙" },
  { "kanji": "追", "reading": { "hiragana": "つい", "katakana": "ツイ" }, "onyomi": "ツイ", "grade": 3, "meaning": "おう", "emoji": "🏃‍♂️" },
  { "kanji": "送", "reading": { "hiragana": "そう", "katakana": "ソウ" }, "onyomi": "ソウ", "grade": 3, "meaning": "おくる", "emoji": "📤" },
  { "kanji": "速", "reading": { "hiragana": "そく", "katakana": "ソク" }, "onyomi": "ソク", "grade": 3, "meaning": "はやい", "emoji": "⚡" },
  { "kanji": "進", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 3, "meaning": "すすむ", "emoji": "🚀" },
  { "kanji": "遊", "reading": { "hiragana": "ゆう", "katakana": "ユウ" }, "onyomi": "ユウ", "grade": 3, "meaning": "あそぶ", "emoji": "🎮" },
  { "kanji": "運", "reading": { "hiragana": "うん", "katakana": "ウン" }, "onyomi": "ウン", "grade": 3, "meaning": "はこぶ", "emoji": "🏋️" },
  { "kanji": "部", "reading": { "hiragana": "ぶ", "katakana": "ブ" }, "onyomi": "ブ", "grade": 3, "meaning": "わける", "emoji": "📚" },
  { "kanji": "都", "reading": { "hiragana": "と", "katakana": "ト" }, "onyomi": "ト", "grade": 3, "meaning": "みやこ", "emoji": "🏙️" },
  { "kanji": "配", "reading": { "hiragana": "はい", "katakana": "ハイ" }, "onyomi": "ハイ", "grade": 3, "meaning": "くばる", "emoji": "📦" },
  { "kanji": "酒", "reading": { "hiragana": "しゅ", "katakana": "シュ" }, "onyomi": "シュ", "grade": 3, "meaning": "さけ", "emoji": "🍶" },
  { "kanji": "重", "reading": { "hiragana": "じゅう", "katakana": "ジュウ" }, "onyomi": "ジュウ", "grade": 3, "meaning": "おもい", "emoji": "🏋️" },
  { "kanji": "鉄", "reading": { "hiragana": "てつ", "katakana": "テツ" }, "onyomi": "テツ", "grade": 3, "meaning": "くろがね", "emoji": "🛤️" },
  { "kanji": "銀", "reading": { "hiragana": "ぎん", "katakana": "ギン" }, "onyomi": "ギン", "grade": 3, "meaning": "しろがね", "emoji": "💰" },
  { "kanji": "開", "reading": { "hiragana": "かい", "katakana": "カイ" }, "onyomi": "カイ", "grade": 3, "meaning": "ひらく", "emoji": "🚪" },
  { "kanji": "院", "reading": { "hiragana": "いん", "katakana": "イン" }, "onyomi": "イン", "grade": 3, "meaning": "いん", "emoji": "🏛️" },
  { "kanji": "陽", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 3, "meaning": "ひ", "emoji": "☀️" },
  { "kanji": "階", "reading": { "hiragana": "かい", "katakana": "カイ" }, "onyomi": "カイ", "grade": 3, "meaning": "きざはし", "emoji": "🏢" },
  { "kanji": "面", "reading": { "hiragana": "めん", "katakana": "メン" }, "onyomi": "メン", "grade": 3, "meaning": "おもて", "emoji": "😐" },
  { "kanji": "題", "reading": { "hiragana": "だい", "katakana": "ダイ" }, "onyomi": "ダイ", "grade": 3, "meaning": "だい", "emoji": "📝" },
  { "kanji": "飲", "reading": { "hiragana": "いん", "katakana": "イン" }, "onyomi": "イン", "grade": 3, "meaning": "のむ", "emoji": "🍵" },
  { "kanji": "館", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 3, "meaning": "やかた", "emoji": "🏛️" },
  { "kanji": "駅", "reading": { "hiragana": "えき", "katakana": "エキ" }, "onyomi": "エキ", "grade": 3, "meaning": "えき", "emoji": "🚉" },
  { "kanji": "愛", "reading": { "hiragana": "あい", "katakana": "アイ" }, "onyomi": "アイ", "grade": 4, "meaning": "あい", "emoji": "❤️" },
  { "kanji": "案", "reading": { "hiragana": "あん", "katakana": "アン" }, "onyomi": "アン", "grade": 4, "meaning": "あん", "emoji": "📝" },
  { "kanji": "以", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 4, "meaning": "もって", "emoji": "🔛" },
  { "kanji": "衣", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 4, "meaning": "ころも", "emoji": "👕" },
  { "kanji": "位", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 4, "meaning": "くらい", "emoji": "🥇" },
  { "kanji": "囲", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 4, "meaning": "かこむ", "emoji": "🔲" },
  { "kanji": "胃", "reading": { "hiragana": "い", "katakana": "イ" }, "onyomi": "イ", "grade": 4, "meaning": "い", "emoji": "🫀" },
  { "kanji": "印", "reading": { "hiragana": "いん", "katakana": "イン" }, "onyomi": "イン", "grade": 4, "meaning": "しるし", "emoji": "🖊️" },
  { "kanji": "英", "reading": { "hiragana": "えい", "katakana": "エイ" }, "onyomi": "エイ", "grade": 4, "meaning": "えい", "emoji": "🇬🇧" },
  { "kanji": "栄", "reading": { "hiragana": "えい", "katakana": "エイ" }, "onyomi": "エイ", "grade": 4, "meaning": "さかえる", "emoji": "🏆" },
  { "kanji": "塩", "reading": { "hiragana": "えん", "katakana": "エン" }, "onyomi": "エン", "grade": 4, "meaning": "しお", "emoji": "🧂" },
  { "kanji": "億", "reading": { "hiragana": "おく", "katakana": "オク" }, "onyomi": "オク", "grade": 4, "meaning": "おく", "emoji": "💵" },
  { "kanji": "加", "reading": { "hiragana": "か", "katakana": "カ" }, "onyomi": "カ", "grade": 4, "meaning": "くわえる", "emoji": "➕" },
  { "kanji": "果", "reading": { "hiragana": "か", "katakana": "カ" }, "onyomi": "カ", "grade": 4, "meaning": "はたす", "emoji": "🍎" },
  { "kanji": "貨", "reading": { "hiragana": "か", "katakana": "カ" }, "onyomi": "カ", "grade": 4, "meaning": "か", "emoji": "💰" },
  { "kanji": "課", "reading": { "hiragana": "か", "katakana": "カ" }, "onyomi": "カ", "grade": 4, "meaning": "か", "emoji": "📚" },
  { "kanji": "芽", "reading": { "hiragana": "が", "katakana": "ガ" }, "onyomi": "ガ", "grade": 4, "meaning": "め", "emoji": "🌱" },
  { "kanji": "改", "reading": { "hiragana": "かい", "katakana": "カイ" }, "onyomi": "カイ", "grade": 4, "meaning": "あらためる", "emoji": "🔄" },
  { "kanji": "械", "reading": { "hiragana": "かい", "katakana": "カイ" }, "onyomi": "カイ", "grade": 4, "meaning": "かい", "emoji": "⚙️" },
  { "kanji": "害", "reading": { "hiragana": "がい", "katakana": "ガイ" }, "onyomi": "ガイ", "grade": 4, "meaning": "がい", "emoji": "⚠️" },
  { "kanji": "街", "reading": { "hiragana": "がい", "katakana": "ガイ" }, "onyomi": "ガイ", "grade": 4, "meaning": "まち", "emoji": "🏙️" },
  { "kanji": "各", "reading": { "hiragana": "かく", "katakana": "カク" }, "onyomi": "カク", "grade": 4, "meaning": "おのおの", "emoji": "👥" },
  { "kanji": "覚", "reading": { "hiragana": "かく", "katakana": "カク" }, "onyomi": "カク", "grade": 4, "meaning": "おぼえる", "emoji": "🧠" },
  { "kanji": "完", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 4, "meaning": "かん", "emoji": "✅" },
  { "kanji": "官", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 4, "meaning": "かん", "emoji": "🏛️" },
  { "kanji": "管", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 4, "meaning": "くだ", "emoji": "🛠️" },
  { "kanji": "関", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 4, "meaning": "かん", "emoji": "🚪" },
  { "kanji": "観", "reading": { "hiragana": "かん", "katakana": "カン" }, "onyomi": "カン", "grade": 4, "meaning": "みる", "emoji": "👀" },
  { "kanji": "願", "reading": { "hiragana": "がん", "katakana": "ガン" }, "onyomi": "ガン", "grade": 4, "meaning": "ねがう", "emoji": "🙏" },
  { "kanji": "希", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 4, "meaning": "まれ", "emoji": "🌟" },
  { "kanji": "季", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 4, "meaning": "き", "emoji": "🍂" },
  { "kanji": "紀", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 4, "meaning": "き", "emoji": "📜" },
  { "kanji": "喜", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 4, "meaning": "よろこぶ", "emoji": "😊" },
  { "kanji": "旗", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 4, "meaning": "はた", "emoji": "🚩" },
  { "kanji": "器", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 4, "meaning": "うつわ", "emoji": "🍶" },
  { "kanji": "機", "reading": { "hiragana": "き", "katakana": "キ" }, "onyomi": "キ", "grade": 4, "meaning": "はた", "emoji": "🛩️" },
  { "kanji": "議", "reading": { "hiragana": "ぎ", "katakana": "ギ" }, "onyomi": "ギ", "grade": 4, "meaning": "ぎ", "emoji": "🗣️" },
  { "kanji": "求", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 4, "meaning": "もとめる", "emoji": "🔍" },
  { "kanji": "泣", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 4, "meaning": "なく", "emoji": "😢" },
  { "kanji": "救", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 4, "meaning": "すくう", "emoji": "🆘" },
  { "kanji": "給", "reading": { "hiragana": "きゅう", "katakana": "キュウ" }, "onyomi": "キュウ", "grade": 4, "meaning": "きゅう", "emoji": "💰" },
  { "kanji": "挙", "reading": { "hiragana": "きょ", "katakana": "キョ" }, "onyomi": "キョ", "grade": 4, "meaning": "あげる", "emoji": "✋" },
  { "kanji": "漁", "reading": { "hiragana": "ぎょ", "katakana": "ギョ" }, "onyomi": "ギョ", "grade": 4, "meaning": "りょう", "emoji": "🎣" },
  { "kanji": "共", "reading": { "hiragana": "きょう", "katakana": "キョウ" }, "onyomi": "キョウ", "grade": 4, "meaning": "とも", "emoji": "👥" },
  { "kanji": "協", "reading": { "hiragana": "きょう", "katakana": "キョウ" }, "onyomi": "キョウ", "grade": 4, "meaning": "きょう", "emoji": "🤝" },
  { "kanji": "鏡", "reading": { "hiragana": "きょう", "katakana": "キョウ" }, "onyomi": "キョウ", "grade": 4, "meaning": "かがみ", "emoji": "🪞" },
  { "kanji": "競", "reading": { "hiragana": "きょう", "katakana": "キョウ" }, "onyomi": "キョウ", "grade": 4, "meaning": "きそう", "emoji": "🏃" },
  { "kanji": "極", "reading": { "hiragana": "きょく", "katakana": "キョク" }, "onyomi": "キョク", "grade": 4, "meaning": "きわめる", "emoji": "⚡" },
  { "kanji": "訓", "reading": { "hiragana": "くん", "katakana": "クン" }, "onyomi": "クン", "grade": 4, "meaning": "くん", "emoji": "📖" },
  { "kanji": "軍", "reading": { "hiragana": "ぐん", "katakana": "グン" }, "onyomi": "グン", "grade": 4, "meaning": "ぐん", "emoji": "⚔️" },
  { "kanji": "郡", "reading": { "hiragana": "ぐん", "katakana": "グン" }, "onyomi": "グン", "grade": 4, "meaning": "ぐん", "emoji": "🏘️" },
  { "kanji": "径", "reading": { "hiragana": "けい", "katakana": "ケイ" }, "onyomi": "ケイ", "grade": 4, "meaning": "けい", "emoji": "📏" },
  { "kanji": "型", "reading": { "hiragana": "けい", "katakana": "ケイ" }, "onyomi": "ケイ", "grade": 4, "meaning": "かた", "emoji": "🧩" },
  { "kanji": "景", "reading": { "hiragana": "けい", "katakana": "ケイ" }, "onyomi": "ケイ", "grade": 4, "meaning": "けしき", "emoji": "🌄" },
  { "kanji": "芸", "reading": { "hiragana": "げい", "katakana": "ゲイ" }, "onyomi": "ゲイ", "grade": 4, "meaning": "げい", "emoji": "🎭" },
  { "kanji": "欠", "reading": { "hiragana": "けつ", "katakana": "ケツ" }, "onyomi": "ケツ", "grade": 4, "meaning": "かける", "emoji": "❌" },
  { "kanji": "結", "reading": { "hiragana": "けつ", "katakana": "ケツ" }, "onyomi": "ケツ", "grade": 4, "meaning": "むすぶ", "emoji": "🎀" },
  { "kanji": "建", "reading": { "hiragana": "けん", "katakana": "ケン" }, "onyomi": "ケン", "grade": 4, "meaning": "たてる", "emoji": "🏗️" },
  { "kanji": "健", "reading": { "hiragana": "けん", "katakana": "ケン" }, "onyomi": "ケン", "grade": 4, "meaning": "けん", "emoji": "💪" },
  { "kanji": "験", "reading": { "hiragana": "けん", "katakana": "ケン" }, "onyomi": "ケン", "grade": 4, "meaning": "けん", "emoji": "🧪" },
  { "kanji": "固", "reading": { "hiragana": "こ", "katakana": "コ" }, "onyomi": "コ", "grade": 4, "meaning": "かたい", "emoji": "🪨" },
  { "kanji": "功", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 4, "meaning": "こう", "emoji": "🏆" },
  { "kanji": "好", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 4, "meaning": "すき", "emoji": "👍" },
  { "kanji": "候", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 4, "meaning": "こう", "emoji": "⏳" },
  { "kanji": "航", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 4, "meaning": "こう", "emoji": "✈️" },
  { "kanji": "康", "reading": { "hiragana": "こう", "katakana": "コウ" }, "onyomi": "コウ", "grade": 4, "meaning": "こう", "emoji": "💊" },
  { "kanji": "告", "reading": { "hiragana": "こく", "katakana": "コク" }, "onyomi": "コク", "grade": 4, "meaning": "つげる", "emoji": "📢" },
  { "kanji": "差", "reading": { "hiragana": "さ", "katakana": "サ" }, "onyomi": "サ", "grade": 4, "meaning": "さ", "emoji": "➖" },
  { "kanji": "最", "reading": { "hiragana": "さい", "katakana": "サイ" }, "onyomi": "サイ", "grade": 4, "meaning": "もっと", "emoji": "🥇" },
  { "kanji": "材", "reading": { "hiragana": "ざい", "katakana": "ザイ" }, "onyomi": "ザイ", "grade": 4, "meaning": "ざい", "emoji": "🪵" },
  { "kanji": "昨", "reading": { "hiragana": "さく", "katakana": "サク" }, "onyomi": "サク", "grade": 4, "meaning": "さく", "emoji": "⏪" },
  { "kanji": "刷", "reading": { "hiragana": "さつ", "katakana": "サツ" }, "onyomi": "サツ", "grade": 4, "meaning": "する", "emoji": "🖨️" },
  { "kanji": "殺", "reading": { "hiragana": "さつ", "katakana": "サツ" }, "onyomi": "サツ", "grade": 4, "meaning": "ころす", "emoji": "⚔️" },
  { "kanji": "察", "reading": { "hiragana": "さつ", "katakana": "サツ" }, "onyomi": "サツ", "grade": 4, "meaning": "さつ", "emoji": "🕵️" },
  { "kanji": "参", "reading": { "hiragana": "さん", "katakana": "サン" }, "onyomi": "サン", "grade": 4, "meaning": "さん", "emoji": "🙏" },
  { "kanji": "産", "reading": { "hiragana": "さん", "katakana": "サン" }, "onyomi": "サン", "grade": 4, "meaning": "うむ", "emoji": "👶" },
  { "kanji": "散", "reading": { "hiragana": "さん", "katakana": "サン" }, "onyomi": "サン", "grade": 4, "meaning": "ちらす", "emoji": "🍂" },
  { "kanji": "残", "reading": { "hiragana": "ざん", "katakana": "ザン" }, "onyomi": "ザン", "grade": 4, "meaning": "のこる", "emoji": "🍽️" },
  { "kanji": "士", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 4, "meaning": "し", "emoji": "🎖️" },
  { "kanji": "氏", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 4, "meaning": "うじ", "emoji": "👨" },
  { "kanji": "史", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 4, "meaning": "し", "emoji": "📜" },
  { "kanji": "司", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 4, "meaning": "し", "emoji": "👨‍⚖️" },
  { "kanji": "試", "reading": { "hiragana": "し", "katakana": "シ" }, "onyomi": "シ", "grade": 4, "meaning": "ためす", "emoji": "📝" },
  { "kanji": "児", "reading": { "hiragana": "じ", "katakana": "ジ" }, "onyomi": "ジ", "grade": 4, "meaning": "こ", "emoji": "👶" },
  { "kanji": "治", "reading": { "hiragana": "じ", "katakana": "ジ" }, "onyomi": "ジ", "grade": 4, "meaning": "なおす", "emoji": "💊" },
  { "kanji": "辞", "reading": { "hiragana": "じ", "katakana": "ジ" }, "onyomi": "ジ", "grade": 4, "meaning": "やめる", "emoji": "📖" },
  { "kanji": "失", "reading": { "hiragana": "しつ", "katakana": "シツ" }, "onyomi": "シツ", "grade": 4, "meaning": "うしなう", "emoji": "❌" },
  { "kanji": "借", "reading": { "hiragana": "しゃく", "katakana": "シャク" }, "onyomi": "シャク", "grade": 4, "meaning": "かりる", "emoji": "💳" },
  { "kanji": "種", "reading": { "hiragana": "しゅ", "katakana": "シュ" }, "onyomi": "シュ", "grade": 4, "meaning": "たね", "emoji": "🌱" },
  { "kanji": "周", "reading": { "hiragana": "しゅう", "katakana": "シュウ" }, "onyomi": "シュウ", "grade": 4, "meaning": "まわり", "emoji": "🔄" },
  { "kanji": "祝", "reading": { "hiragana": "しゅく", "katakana": "シュク" }, "onyomi": "シュク", "grade": 4, "meaning": "いわう", "emoji": "🎉" },
  { "kanji": "順", "reading": { "hiragana": "じゅん", "katakana": "ジュン" }, "onyomi": "ジュン", "grade": 4, "meaning": "じゅん", "emoji": "🔢" },
  { "kanji": "初", "reading": { "hiragana": "しょ", "katakana": "ショ" }, "onyomi": "ショ", "grade": 4, "meaning": "はじめ", "emoji": "1️⃣" },
  { "kanji": "省", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 4, "meaning": "はぶく", "emoji": "🏛️" },
  { "kanji": "照", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 4, "meaning": "てる", "emoji": "🔦" },
  { "kanji": "賞", "reading": { "hiragana": "しょう", "katakana": "ショウ" }, "onyomi": "ショウ", "grade": 4, "meaning": "しょう", "emoji": "🏆" },
  { "kanji": "臣", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 4, "meaning": "しん", "emoji": "👨‍💼" },
  { "kanji": "信", "reading": { "hiragana": "しん", "katakana": "シン" }, "onyomi": "シン", "grade": 4, "meaning": "しん", "emoji": "✉️" },
  { "kanji": "成", "reading": { "hiragana": "せい", "katakana": "セイ" }, "onyomi": "セイ", "grade": 4, "meaning": "なる", "emoji": "✅" },
  { "kanji": "省", "reading": { "hiragana": "せい", "katakana": "セイ" }, "onyomi": "セイ", "grade": 4, "meaning": "はぶく", "emoji": "🏛️" },
  { "kanji": "清", "reading": { "hiragana": "せい", "katakana": "セイ" }, "onyomi": "セイ", "grade": 4, "meaning": "きよい", "emoji": "💧" },
  { "kanji": "静", "reading": { "hiragana": "せい", "katakana": "セイ" }, "onyomi": "セイ", "grade": 4, "meaning": "しずか", "emoji": "🤫" },
  { "kanji": "席", "reading": { "hiragana": "せき", "katakana": "セキ" }, "onyomi": "セキ", "grade": 4, "meaning": "せき", "emoji": "💺" },
  { "kanji": "積", "reading": { "hiragana": "せき", "katakana": "セキ" }, "onyomi": "セキ", "grade": 4, "meaning": "つむ", "emoji": "📦" },
  { "kanji": "折", "reading": { "hiragana": "せつ", "katakana": "セツ" }, "onyomi": "セツ", "grade": 4, "meaning": "おる", "emoji": "📉" },
  { "kanji": "節", "reading": { "hiragana": "せつ", "katakana": "セツ" }, "onyomi": "セツ", "grade": 4, "meaning": "ふし", "emoji": "🎋" },
  { "kanji": "説", "reading": { "hiragana": "せつ", "katakana": "セツ" }, "onyomi": "セツ", "grade": 4, "meaning": "とく", "emoji": "🗣️" },
  { "kanji": "浅", "reading": { "hiragana": "せん", "katakana": "セン" }, "onyomi": "セン", "grade": 4, "meaning": "あさい", "emoji": "🏖️" },
  { "kanji": "戦", "reading": { "hiragana": "せん", "katakana": "セン" }, "onyomi": "セン", "grade": 4, "meaning": "たたかう", "emoji": "⚔️" },
  { "kanji": "選", "reading": { "hiragana": "せん", "katakana": "セン" }, "onyomi": "セン", "grade": 4, "meaning": "えらぶ", "emoji": "🗳️" },
  { "kanji": "然", "reading": { "hiragana": "ぜん", "katakana": "ゼン" }, "onyomi": "ゼン", "grade": 4, "meaning": "しかり", "emoji": "🔥" },
  { "kanji": "争", "reading": { "hiragana": "そう", "katakana": "ソウ" }, "onyomi": "ソウ", "grade": 4, "meaning": "あらそう", "emoji": "⚔️" },
  { "kanji": "倉", "reading": { "hiragana": "そう", "katakana": "ソウ" }, "onyomi": "ソウ", "grade": 4, "meaning": "くら", "emoji": "🏚️" },
  { "kanji": "巣", "reading": { "hiragana": "そう", "katakana": "ソウ" }, "onyomi": "ソウ", "grade": 4, "meaning": "す", "emoji": "🐦" },
  { "kanji": "束", "reading": { "hiragana": "そく", "katakana": "ソク" }, "onyomi": "ソク", "grade": 4, "meaning": "たば", "emoji": "📦" },
  { "kanji": "側", "reading": { "hiragana": "そく", "katakana": "ソク" }, "onyomi": "ソク", "grade": 4, "meaning": "がわ", "emoji": "↔️" },
  { "kanji": "続", "reading": { "hiragana": "ぞく", "katakana": "ゾク" }, "onyomi": "ゾク", "grade": 4, "meaning": "つづく", "emoji": "🔁" },
  { "kanji": "孫", "reading": { "hiragana": "そん", "katakana": "ソン" }, "onyomi": "ソン", "grade": 4, "meaning": "まご", "emoji": "👴" },
  { "kanji": "帯", "reading": { "hiragana": "たい", "katakana": "タイ" }, "onyomi": "タイ", "grade": 4, "meaning": "おび", "emoji": "🎀" },
  { "kanji": "隊", "reading": { "hiragana": "たい", "katakana": "タイ" }, "onyomi": "タイ", "grade": 4, "meaning": "たい", "emoji": "👥" },
  { "kanji": "達", "reading": { "hiragana": "たつ", "katakana": "タツ" }, "onyomi": "タツ", "grade": 4, "meaning": "たち", "emoji": "👥" },
  { "kanji": "単", "reading": { "hiragana": "たん", "katakana": "タン" }, "onyomi": "タン", "grade": 4, "meaning": "ひとえ", "emoji": "1️⃣" },
  { "kanji": "置", "reading": { "hiragana": "ち", "katakana": "チ" }, "onyomi": "チ", "grade": 4, "meaning": "おく", "emoji": "📍" },
  { "kanji": "仲", "reading": { "hiragana": "ちゅう", "katakana": "チュウ" }, "onyomi": "チュウ", "grade": 4, "meaning": "なか", "emoji": "👬" },
  { "kanji": "貯", "reading": { "hiragana": "ちょ", "katakana": "チョ" }, "onyomi": "チョ", "grade": 4, "meaning": "たくわえる", "emoji": "💰" },
  { "kanji": "兆", "reading": { "hiragana": "ちょう", "katakana": "チョウ" }, "onyomi": "チョウ", "grade": 4, "meaning": "きざす", "emoji": "🔮" },
  { "kanji": "腸", "reading": { "hiragana": "ちょう", "katakana": "チョウ" }, "onyomi": "チョウ", "grade": 4, "meaning": "はらわた", "emoji": "🫀" },
  { "kanji": "低", "reading": { "hiragana": "てい", "katakana": "テイ" }, "onyomi": "テイ", "grade": 4, "meaning": "ひくい", "emoji": "📉" },
  { "kanji": "底", "reading": { "hiragana": "てい", "katakana": "テイ" }, "onyomi": "テイ", "grade": 4, "meaning": "そこ", "emoji": "⬇️" },
  { "kanji": "停", "reading": { "hiragana": "てい", "katakana": "テイ" }, "onyomi": "テイ", "grade": 4, "meaning": "とめる", "emoji": "🛑" },
  { "kanji": "的", "reading": { "hiragana": "てき", "katakana": "テキ" }, "onyomi": "テキ", "grade": 4, "meaning": "まと", "emoji": "🎯" },
  { "kanji": "典", "reading": { "hiragana": "てん", "katakana": "テン" }, "onyomi": "テン", "grade": 4, "meaning": "てん", "emoji": "📚" },
  { "kanji": "伝", "reading": { "hiragana": "でん", "katakana": "デン" }, "onyomi": "デン", "grade": 4, "meaning": "つたえる", "emoji": "📢" },
  { "kanji": "徒", "reading": { "hiragana": "と", "katakana": "ト" }, "onyomi": "ト", "grade": 4, "meaning": "ただ", "emoji": "🚶" },
  { "kanji": "努", "reading": { "hiragana": "ど", "katakana": "ド" }, "onyomi": "ド", "grade": 4, "meaning": "つとめる", "emoji": "💪" },
  { "kanji": "灯", "reading": { "hiragana": "とう", "katakana": "トウ" }, "onyomi": "トウ", "grade": 4, "meaning": "ひ", "emoji": "🪔" },
  { "kanji": "堂", "reading": { "hiragana": "どう", "katakana": "ドウ" }, "onyomi": "ドウ", "grade": 4, "meaning": "どう", "emoji": "🏛️" },
  { "kanji": "働", "reading": { "hiragana": "どう", "katakana": "ドウ" }, "onyomi": "ドウ", "grade": 4, "meaning": "はたらく", "emoji": "💼" },
  { "kanji": "特", "reading": { "hiragana": "とく", "katakana": "トク" }, "onyomi": "トク", "grade": 4, "meaning": "とく", "emoji": "🌟" },
  { "kanji": "得", "reading": { "hiragana": "とく", "katakana": "トク" }, "onyomi": "トク", "grade": 4, "meaning": "える", "emoji": "🉐" },
  { "kanji": "毒", "reading": { "hiragana": "どく", "katakana": "ドク" }, "onyomi": "ドク", "grade": 4, "meaning": "どく", "emoji": "☠️" },
  { "kanji": "熱", "reading": { "hiragana": "ねつ", "katakana": "ネツ" }, "onyomi": "ネツ", "grade": 4, "meaning": "あつい", "emoji": "🌡️" },
  { "kanji": "念", "reading": { "hiragana": "ねん", "katakana": "ネン" }, "onyomi": "ネン", "grade": 4, "meaning": "ねん", "emoji": "🧠" },
  { "kanji": "敗", "reading": { "hiragana": "はい", "katakana": "ハイ" }, "onyomi": "ハイ", "grade": 4, "meaning": "やぶれる", "emoji": "❌" },
  { "kanji": "梅", "reading": { "hiragana": "ばい", "katakana": "バイ" }, "onyomi": "バイ", "grade": 4, "meaning": "うめ", "emoji": "🌸" },
  { "kanji": "博", "reading": { "hiragana": "はく", "katakana": "ハク" }, "onyomi": "ハク", "grade": 4, "meaning": "ひろい", "emoji": "🎓" },
  { "kanji": "飯", "reading": { "hiragana": "はん", "katakana": "ハン" }, "onyomi": "ハン", "grade": 4, "meaning": "めし", "emoji": "🍚" },
  { "kanji": "飛", "reading": { "hiragana": "ひ", "katakana": "ヒ" }, "onyomi": "ヒ", "grade": 4, "meaning": "とぶ", "emoji": "✈️" },
  { "kanji": "費", "reading": { "hiragana": "ひ", "katakana": "ヒ" }, "onyomi": "ヒ", "grade": 4, "meaning": "ついやす", "emoji": "💰" },
  { "kanji": "必", "reading": { "hiragana": "ひつ", "katakana": "ヒツ" }, "onyomi": "ヒツ", "grade": 4, "meaning": "かならず", "emoji": "❗" },
  { "kanji": "票", "reading": { "hiragana": "ひょう", "katakana": "ヒョウ" }, "onyomi": "ヒョウ", "grade": 4, "meaning": "ひょう", "emoji": "🗳️" },
  { "kanji": "標", "reading": { "hiragana": "ひょう", "katakana": "ヒョウ" }, "onyomi": "ヒョウ", "grade": 4, "meaning": "しるべ", "emoji": "📍" },
  { "kanji": "不", "reading": { "hiragana": "ふ", "katakana": "フ" }, "onyomi": "フ", "grade": 4, "meaning": "ず", "emoji": "❌" },
  { "kanji": "夫", "reading": { "hiragana": "ふ", "katakana": "フ" }, "onyomi": "フ", "grade": 4, "meaning": "おっと", "emoji": "👨" },
  { "kanji": "付", "reading": { "hiragana": "ふ", "katakana": "フ" }, "onyomi": "フ", "grade": 4, "meaning": "つける", "emoji": "➕" },
  { "kanji": "府", "reading": { "hiragana": "ふ", "katakana": "フ" }, "onyomi": "フ", "grade": 4, "meaning": "ふ", "emoji": "🏛️" },
  { "kanji": "副", "reading": { "hiragana": "ふく", "katakana": "フク" }, "onyomi": "フク", "grade": 4, "meaning": "そえる", "emoji": "🥈" },
  { "kanji": "粉", "reading": { "hiragana": "ふん", "katakana": "フン" }, "onyomi": "フン", "grade": 4, "meaning": "こな", "emoji": "🌾" },
  { "kanji": "兵", "reading": { "hiragana": "へい", "katakana": "ヘイ" }, "onyomi": "ヘイ", "grade": 4, "meaning": "へい", "emoji": "⚔️" },
  { "kanji": "別", "reading": { "hiragana": "べつ", "katakana": "ベツ" }, "onyomi": "ベツ", "grade": 4, "meaning": "わかれる", "emoji": "👋" },
  { "kanji": "辺", "reading": { "hiragana": "へん", "katakana": "ヘン" }, "onyomi": "ヘン", "grade": 4, "meaning": "あたり", "emoji": "📍" },
  { "kanji": "変", "reading": { "hiragana": "へん", "katakana": "ヘン" }, "onyomi": "ヘン", "grade": 4, "meaning": "かわる", "emoji": "🔄" },
  { "kanji": "便", "reading": { "hiragana": "べん", "katakana": "ベン" }, "onyomi": "ベン", "grade": 4, "meaning": "たより", "emoji": "✉️" },
  { "kanji": "包", "reading": { "hiragana": "ほう", "katakana": "ホウ" }, "onyomi": "ホウ", "grade": 4, "meaning": "つつむ", "emoji": "🎁" },
  { "kanji": "法", "reading": { "hiragana": "ほう", "katakana": "ホウ" }, "onyomi": "ホウ", "grade": 4, "meaning": "ほう", "emoji": "⚖️" },
  { "kanji": "望", "reading": { "hiragana": "ぼう", "katakana": "ボウ" }, "onyomi": "ボウ", "grade": 4, "meaning": "のぞむ", "emoji": "🌠" },
  { "kanji": "牧", "reading": { "hiragana": "ぼく", "katakana": "ボク" }, "onyomi": "ボク", "grade": 4, "meaning": "まき", "emoji": "🐄" },
  { "kanji": "末", "reading": { "hiragana": "まつ", "katakana": "マツ" }, "onyomi": "マツ", "grade": 4, "meaning": "すえ", "emoji": "🔚" },
  { "kanji": "満", "reading": { "hiragana": "まん", "katakana": "マン" }, "onyomi": "マン", "grade": 4, "meaning": "みちる", "emoji": "🈵" },
  { "kanji": "脈", "reading": { "hiragana": "みゃく", "katakana": "ミャク" }, "onyomi": "ミャク", "grade": 4, "meaning": "みゃく", "emoji": "💓" },
  { "kanji": "民", "reading": { "hiragana": "みん", "katakana": "ミン" }, "onyomi": "ミン", "grade": 4, "meaning": "たみ", "emoji": "👥" },
  { "kanji": "無", "reading": { "hiragana": "む", "katakana": "ム" }, "onyomi": "ム", "grade": 4, "meaning": "ない", "emoji": "🈚" },
  { "kanji": "約", "reading": { "hiragana": "やく", "katakana": "ヤク" }, "onyomi": "ヤク", "grade": 4, "meaning": "やく", "emoji": "🤝" },
  { "kanji": "勇", "reading": { "hiragana": "ゆう", "katakana": "ユウ" }, "onyomi": "ユウ", "grade": 4, "meaning": "いさむ", "emoji": "💪" },
  { "kanji": "要", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 4, "meaning": "いる", "emoji": "❗" },
  { "kanji": "養", "reading": { "hiragana": "よう", "katakana": "ヨウ" }, "onyomi": "ヨウ", "grade": 4, "meaning": "やしなう", "emoji": "🍼" },
  { "kanji": "浴", "reading": { "hiragana": "よく", "katakana": "ヨク" }, "onyomi": "ヨク", "grade": 4, "meaning": "あびる", "emoji": "🛁" },
  { "kanji": "利", "reading": { "hiragana": "り", "katakana": "リ" }, "onyomi": "リ", "grade": 4, "meaning": "きく", "emoji": "💹" },
  { "kanji": "陸", "reading": { "hiragana": "りく", "katakana": "リク" }, "onyomi": "リク", "grade": 4, "meaning": "りく", "emoji": "🌍" },
  { "kanji": "良", "reading": { "hiragana": "りょう", "katakana": "リョウ" }, "onyomi": "リョウ", "grade": 4, "meaning": "よい", "emoji": "👍" },
  { "kanji": "料", "reading": { "hiragana": "りょう", "katakana": "リョウ" }, "onyomi": "リョウ", "grade": 4, "meaning": "りょう", "emoji": "💰" },
  { "kanji": "輪", "reading": { "hiragana": "りん", "katakana": "リン" }, "onyomi": "リン", "grade": 4, "meaning": "わ", "emoji": "🔄" },
  { "kanji": "類", "reading": { "hiragana": "るい", "katakana": "ルイ" }, "onyomi": "ルイ", "grade": 4, "meaning": "たぐい", "emoji": "📚" },
  { "kanji": "令", "reading": { "hiragana": "れい", "katakana": "レイ" }, "onyomi": "レイ", "grade": 4, "meaning": "れい", "emoji": "📜" },
  { "kanji": "冷", "reading": { "hiragana": "れい", "katakana": "レイ" }, "onyomi": "レイ", "grade": 4, "meaning": "つめたい", "emoji": "❄️" },
  { "kanji": "例", "reading": { "hiragana": "れい", "katakana": "レイ" }, "onyomi": "レイ", "grade": 4, "meaning": "たとえる", "emoji": "📖" },
  { "kanji": "歴", "reading": { "hiragana": "れき", "katakana": "レキ" }, "onyomi": "レキ", "grade": 4, "meaning": "れき", "emoji": "📜" },
  { "kanji": "連", "reading": { "hiragana": "れん", "katakana": "レン" }, "onyomi": "レン", "grade": 4, "meaning": "つらなる", "emoji": "🔗" },
  { "kanji": "老", "reading": { "hiragana": "ろう", "katakana": "ロウ" }, "onyomi": "ロウ", "grade": 4, "meaning": "おいる", "emoji": "👴" },
  { "kanji": "労", "reading": { "hiragana": "ろう", "katakana": "ロウ" }, "onyomi": "ロウ", "grade": 4, "meaning": "ろう", "emoji": "💼" },
  { "kanji": "録", "reading": { "hiragana": "ろく", "katakana": "ロク" }, "onyomi": "ロク", "grade": 4, "meaning": "しるす", "emoji": "📼" }
];
